/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package N23DCCN058.fm.ui.panel;

import N23DCCN058.fm.exception.ServiceException;
import N23DCCN058.fm.exception.ValidationException;
import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.PlayerPosition;
import N23DCCN058.fm.model.PlayerStatistic;
import N23DCCN058.fm.model.Team;
import N23DCCN058.fm.service.PlayerService;
import N23DCCN058.fm.service.StatisticService;
import N23DCCN058.fm.service.TeamService;
import N23DCCN058.fm.ui.dialog.CapNhapThongTinCauThuDialog;
import N23DCCN058.fm.ui.dialog.ThemCauThuDialog;
import N23DCCN058.fm.ui.dialog.TimCauThuDialog;
import N23DCCN058.fm.ui.dialog.TimCauThuTheoTenDoiBongDialog;
import N23DCCN058.fm.ui.frame.MainFrame;
import N23DCCN058.fm.ui.frame.ScreenManager;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author admin
 */
public class CauThuPanel extends javax.swing.JPanel {
    /**
     * Creates new form CauThuPanel
     */
    DefaultTableModel model;
    
    public CauThuPanel() {
        initComponents();
        setSize(1000,600);
        initTableModel();
        initTableSelectionListener();
        updateButtonVisibility();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnDanhSach = new javax.swing.JButton();
        btnThemCauThu = new javax.swing.JButton();
        btnSuaThongTin = new javax.swing.JButton();
        btnXoaCauThu = new javax.swing.JButton();
        btnXemChiTiet = new javax.swing.JButton();
        btnTimKiemTheoDoi = new javax.swing.JButton();
        btnXemThongSo = new javax.swing.JButton();
        btnTimCauThu = new javax.swing.JButton();
        panelMenu13 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        btnFM9 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        panelHome.setBackground(new java.awt.Color(0, 76, 127));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setPreferredSize(new java.awt.Dimension(1000, 600));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(450, 402));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        btnDanhSach.setBackground(new java.awt.Color(0, 76, 127));
        btnDanhSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDanhSach.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSach.setText("DANH SÁCH CẦU THỦ");
        btnDanhSach.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachActionPerformed(evt);
            }
        });

        btnThemCauThu.setBackground(new java.awt.Color(0, 76, 127));
        btnThemCauThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemCauThu.setForeground(new java.awt.Color(255, 255, 255));
        btnThemCauThu.setText("THÊM CẦU THỦ");
        btnThemCauThu.setToolTipText("");
        btnThemCauThu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnThemCauThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCauThuActionPerformed(evt);
            }
        });

        btnSuaThongTin.setBackground(new java.awt.Color(0, 76, 127));
        btnSuaThongTin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaThongTin.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaThongTin.setText("SỬA THÔNG TIN");
        btnSuaThongTin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThongTinActionPerformed(evt);
            }
        });

        btnXoaCauThu.setBackground(new java.awt.Color(0, 76, 127));
        btnXoaCauThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaCauThu.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaCauThu.setText("XÓA CẦU THỦ");
        btnXoaCauThu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnXoaCauThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCauThuActionPerformed(evt);
            }
        });

        btnXemChiTiet.setBackground(new java.awt.Color(0, 76, 127));
        btnXemChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXemChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnXemChiTiet.setText("XEM CHI TIẾT ĐỘI");
        btnXemChiTiet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        btnTimKiemTheoDoi.setBackground(new java.awt.Color(0, 76, 127));
        btnTimKiemTheoDoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiemTheoDoi.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiemTheoDoi.setText("TÌM KIẾM THEO ĐỘI");
        btnTimKiemTheoDoi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnTimKiemTheoDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemTheoDoiActionPerformed(evt);
            }
        });

        btnXemThongSo.setBackground(new java.awt.Color(0, 76, 127));
        btnXemThongSo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXemThongSo.setForeground(new java.awt.Color(255, 255, 255));
        btnXemThongSo.setText("XEM THÔNG SỐ");
        btnXemThongSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemThongSoActionPerformed(evt);
            }
        });

        btnTimCauThu.setBackground(new java.awt.Color(0, 76, 127));
        btnTimCauThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimCauThu.setForeground(new java.awt.Color(255, 255, 255));
        btnTimCauThu.setText("TÌM CẦU THỦ");
        btnTimCauThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimCauThuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemCauThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaCauThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXemChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimKiemTheoDoi, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(btnXemThongSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimCauThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnThemCauThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiemTheoDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimCauThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnXemThongSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaCauThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnXemChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        panelMenu13.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu13.setPreferredSize(new java.awt.Dimension(1000, 40));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Untitled-3.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnFM9.setBackground(new java.awt.Color(0, 0, 0));
        btnFM9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFM9.setForeground(new java.awt.Color(255, 255, 255));
        btnFM9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Artboard 2.png"))); // NOI18N
        btnFM9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFM9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFM9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFM9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu13Layout = new javax.swing.GroupLayout(panelMenu13);
        panelMenu13.setLayout(panelMenu13Layout);
        panelMenu13Layout.setHorizontalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFM9)
                .addContainerGap())
        );
        panelMenu13Layout.setVerticalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFM9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(panelMenu13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(panelMenu13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );

        add(panelHome);
    }// </editor-fold>//GEN-END:initComponents

    private void initTableModel(){
        String[] columnNames = {"Id", "Tên cầu thủ", "Ngày sinh", "Số áo", "Vị trí", "Id đội"};
        model = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(model);
        
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel col = jTable1.getColumnModel();
        
        col.getColumn(0).setPreferredWidth(50); // Id cầu thủ
        col.getColumn(1).setPreferredWidth(200); // Tên cầu thủ
        col.getColumn(2).setPreferredWidth(100); // Ngày sinh
        col.getColumn(3).setPreferredWidth(80);  // Số áo
        col.getColumn(4).setPreferredWidth(140); // Vị trí
        col.getColumn(5).setPreferredWidth(50); // Id đội
        
        for (int i = 0; i < col.getColumnCount(); i++) {
            col.getColumn(i).setResizable(false);
        }
    }
    
    private void initTableSelectionListener(){
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { // Đảm bảo chỉ xử lý khi chọn xong
                updateButtonVisibility();
            }   
        }); 
    }
    
    private void updateButtonVisibility() {
        int selectedCount = jTable1.getSelectedRowCount();

                // Nếu chưa chọn hoặc chọn > 1 dòng -> disable nút
        boolean enable = (selectedCount == 1);
        btnXemThongSo.setEnabled(enable);
        btnSuaThongTin.setEnabled(enable);
        btnXemChiTiet.setEnabled(enable);
        btnXoaCauThu.setEnabled(enable);
    }
    
    void resetTableData(){
        model.setRowCount(0);
    }
    
    private void hienDanhSach(){
        PlayerService pService = new PlayerService();
        try {
            List<Player>list = pService.getAllPlayer();
            hienDanhSach(list);
        } catch (ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Không thể lấy dữ liệu!", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    
    public void showPlayerOfTeam(int teamId){
        TeamService tService = new TeamService();
        try {
            List<Player> list = tService.getPlayersOfTeam(teamId);
            hienDanhSach(list);
        } catch (ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Không thể lấy dữ liệu!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void hienDanhSach(List<Player> list){
        resetTableData();
        for(Player player : list) model.addRow(player.toObjectArray());

        model.fireTableDataChanged();
        jTable1.revalidate();
        jTable1.repaint();
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }
    
    
    
    private void btnDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachActionPerformed
        hienDanhSach();
    }//GEN-LAST:event_btnDanhSachActionPerformed

    private void btnSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThongTinActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ bóng để sửa!");
            return;
        }

        int id = (int) jTable1.getValueAt(selectedRow, 0);
        String name = jTable1.getValueAt(selectedRow, 1).toString();
        Date dob = (Date) jTable1.getValueAt(selectedRow, 2);
        int jerseyNumber = (int) jTable1.getValueAt(selectedRow, 3);
        PlayerPosition position = PlayerPosition.fromString(jTable1.getValueAt(selectedRow, 4).toString());
        int teamId = (int) jTable1.getValueAt(selectedRow, 5);

        Player player = new Player(id, name, dob, jerseyNumber, position, teamId);

        CapNhapThongTinCauThuDialog dialog = new CapNhapThongTinCauThuDialog(mainFrame, true, player);
        dialog.setVisible(true);

        if(!dialog.isConfirm()) return;

        try {
            PlayerService pService = new PlayerService();
            Player updatedPlayer = dialog.getPlayerFromTextFields();
            pService.updatePlayer(updatedPlayer);
            hienDanhSach();
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaThongTinActionPerformed

    private void btnThemCauThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCauThuActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ThemCauThuDialog dialog = new ThemCauThuDialog(mainFrame, true);
        //dialog.setVisible(true);
        if (mainFrame != null) {
        // Tạo GlassPane làm mờ
            final javax.swing.JPanel glassPane = new javax.swing.JPanel() {
            @Override
                protected void paintComponent(java.awt.Graphics g) {
                    super.paintComponent(g);
                // Vẽ lớp phủ màu đen trong suốt
                    g.setColor(new java.awt.Color(0, 0, 0, 128)); // 128 = 50% opacity
                    g.fillRect(0, 0, getWidth(), getHeight());
                }
            };
        
        glassPane.setOpaque(false);
        // Chặn tương tác với các component bên dưới
        glassPane.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                dialog.dispose();// Click vào vùng mờ sẽ đóng dialog
            }
        });
        
        // Đặt glassPane
        mainFrame.setGlassPane(glassPane);
        glassPane.setVisible(true);
        
        // Hiển thị dialog
        
        
        // Thêm listener để tắt glassPane khi đóng dialog
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                glassPane.setVisible(false);
            }
        });
        
        
        dialog.setVisible(true);
    }
        
        if(!dialog.isConfirm()) return;
        
        try {
            PlayerService ps = new PlayerService();
            Player player = dialog.getPlayerFromTextFields();
            ps.addPlayer(player);
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
        hienDanhSach();
    }//GEN-LAST:event_btnThemCauThuActionPerformed

    private void btnTimCauThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimCauThuActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        TimCauThuDialog dialog = new TimCauThuDialog(mainFrame, true);
        //dialog.setVisible(true);
        if (mainFrame != null) {
        // Tạo GlassPane làm mờ
            final javax.swing.JPanel glassPane = new javax.swing.JPanel() {
            @Override
                protected void paintComponent(java.awt.Graphics g) {
                    super.paintComponent(g);
                // Vẽ lớp phủ màu đen trong suốt
                    g.setColor(new java.awt.Color(0, 0, 0, 128)); // 128 = 50% opacity
                    g.fillRect(0, 0, getWidth(), getHeight());
                }
            };
        
        glassPane.setOpaque(false);
        // Chặn tương tác với các component bên dưới
        glassPane.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                dialog.dispose();// Click vào vùng mờ sẽ đóng dialog
            }
        });
        
        // Đặt glassPane
        mainFrame.setGlassPane(glassPane);
        glassPane.setVisible(true);
        
        // Hiển thị dialog
        
        
        // Thêm listener để tắt glassPane khi đóng dialog
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                glassPane.setVisible(false);
            }
        });
        
        
        dialog.setVisible(true);
    }
        
        if(!dialog.isConfirm()) return;
        
        try {
            PlayerService ps = new PlayerService();
            Player player = dialog.getPlayerFromTextFields();
            List<Player> ds = ps.searchPlayer(player);
            hienDanhSach(ds);
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimCauThuActionPerformed

    private void btnXoaCauThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCauThuActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa cầu thủ này không?\n Xóa cầu thủ sẽ xóa toàn bộ thông tin liên quan!",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );   
        if(choice != JOptionPane.YES_OPTION) return;
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ bóng để xóa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        try {
            PlayerService ps = new PlayerService();
            ps.deletePlayerById(id);
            hienDanhSach();
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaCauThuActionPerformed

    private void btnTimKiemTheoDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemTheoDoiActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        TimCauThuTheoTenDoiBongDialog dialog = new TimCauThuTheoTenDoiBongDialog(mainFrame, true);
        //dialog.setVisible(true);
        if (mainFrame != null) {
        // Tạo GlassPane làm mờ
            final javax.swing.JPanel glassPane = new javax.swing.JPanel() {
            @Override
                protected void paintComponent(java.awt.Graphics g) {
                    super.paintComponent(g);
                // Vẽ lớp phủ màu đen trong suốt
                    g.setColor(new java.awt.Color(0, 0, 0, 128)); // 128 = 50% opacity
                    g.fillRect(0, 0, getWidth(), getHeight());
                }
            };
        
        glassPane.setOpaque(false);
        // Chặn tương tác với các component bên dưới
        glassPane.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                dialog.dispose();// Click vào vùng mờ sẽ đóng dialog
            }
        });
        
        // Đặt glassPane
        mainFrame.setGlassPane(glassPane);
        glassPane.setVisible(true);
        
        // Hiển thị dialog
        
        
        // Thêm listener để tắt glassPane khi đóng dialog
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                glassPane.setVisible(false);
            }
        });
        
        
        dialog.setVisible(true);
    }
        if(!dialog.isConfirm()) return;
        
        try {
            PlayerService ps = new PlayerService();
            int teamId = dialog.getTeamId();
            List<Player> ds = ps.getPlayersByTeamID(teamId);
            hienDanhSach(ds);
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimKiemTheoDoiActionPerformed

    private void btnFM9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFM9ActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ScreenManager.get().clearHistory();
        if (mainFrame != null) {
            mainFrame.showHome();
        }
    }//GEN-LAST:event_btnFM9ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        resetTableData();
        ScreenManager.get().back();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnXemThongSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemThongSoActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ để sửa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        
        try {
            StatisticService ss = new StatisticService();
            PlayerService pService = new PlayerService();
            PlayerStatistic ps = ss.getPlayerStatistic(id);
            Player player = pService.getPlayerById(id);
            String info = "Tên cầu thủ: " + player.getPlayerName() + "\n" 
                        + "Vị trí: " + player.getPosition().name() + "\n"
                        + "Số áo: " + player.getJerseyNumber() + "\n" 
                        + "Số trận đã chơi: " + ps.getNumOfPlayedMatches() + "\n"
                        + "Số lần trong đội hình đá chính: " + ps.getNumOfStartingRole() + "\n"
                        + "Tổng thời gian thi đấu: " + ps.getTotalPlayedTime() + "\n" 
                        + "Số bàn thắng đã ghi: " + ps.getNumOfGoals() + "\n"
                        + "Số bàn thắng bằng penalty: " + ps.getNumOfPenaltyGoals() + "\n"
                        + "Số lần phản lưới nhà: " + ps.getNumOfOwnGoals() + "\n"
                        + "Số lần phạm lỗi: " + ps.getNumOfFouls() + "\n"
                        + "Số thẻ vàng đã nhận: " + ps.getNumOfYellowCards() + "\n"
                        + "Số thẻ đỏ đã nhận: " + ps.getNumOfRedCards();
            JOptionPane.showMessageDialog(this, info, "Thông số cầu thủ" , JOptionPane.INFORMATION_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnXemThongSoActionPerformed

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ để sửa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 5);
        
        try {
            TeamService ts = new TeamService();
            Team team = ts.getTeamById(id);
            String info = "Id: " + team.getTeamId() + "\n" 
                        + "Tên đội bóng: " + team.getTeamName() + "\n"
                        + "Khoa: " + team.getDepartment() + "\n"
                        + "Huấn luyện viên: " + team.getCoachName();
            JOptionPane.showMessageDialog(this, info, "Thông tin đội" , JOptionPane.INFORMATION_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXemChiTietActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSach;
    private javax.swing.JButton btnFM9;
    private javax.swing.JButton btnSuaThongTin;
    private javax.swing.JButton btnThemCauThu;
    private javax.swing.JButton btnTimCauThu;
    private javax.swing.JButton btnTimKiemTheoDoi;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JButton btnXemThongSo;
    private javax.swing.JButton btnXoaCauThu;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu13;
    // End of variables declaration//GEN-END:variables
}
