/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package N23DCCN058.fm.ui.panel;

import N23DCCN058.fm.model.MatchPlayers;
import N23DCCN058.fm.model.MatchTeams;
import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.PlayerRole;
import N23DCCN058.fm.model.TeamRole;
import N23DCCN058.fm.service.MatchEventService;
import N23DCCN058.fm.service.MatchPlayerService;
import N23DCCN058.fm.service.MatchService;
import N23DCCN058.fm.service.MatchTeamService;
import N23DCCN058.fm.service.PlayerService;
import N23DCCN058.fm.service.TeamService;
import N23DCCN058.fm.ui.dialog.ChonDoiDialog;
import N23DCCN058.fm.ui.dialog.ChonDoiHinhDialog;
import N23DCCN058.fm.ui.frame.MainFrame;
import N23DCCN058.fm.ui.frame.ScreenManager;
import java.util.List;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author admin
 */
public class ChiTietTranDauPanel extends javax.swing.JPanel {

    /**
     * Creates new form CaiDatPanel
     */
    
    private static final String CHUA_XAC_DINH = "[Chưa xác định]";
    private int matchId, idDoiNha, idDoiKhach;
    private DefaultTableModel modelDoiNha, modelDoiKhach;
    private boolean isMatchFinish, isSelectedTeam;
    private List<MatchPlayers> doiNha, doiKhach;
    private boolean isSelectedPlayerHome, isSelectedPlayerAway;

    
    
    public ChiTietTranDauPanel(int matchId) {
        initComponents();
        
        this.matchId = matchId;
        
        String[] columnNames= {"Tên cầu thủ", "Vị trí", "Vai trò"};
        modelDoiNha = new DefaultTableModel(columnNames, 0);
        modelDoiKhach = new DefaultTableModel(columnNames, 0);
        tbDoiNha.setModel(modelDoiNha);
        tbDoiKhach.setModel(modelDoiKhach);
        
        tbDoiNha.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel colHome = tbDoiNha.getColumnModel();
        
        colHome.getColumn(0).setPreferredWidth(140); // Tên cầu thủ
        colHome.getColumn(1).setPreferredWidth(112); // Vị trí
        colHome.getColumn(2).setPreferredWidth(70); // Vai trò
        
        for (int i = 0; i < colHome.getColumnCount(); i++) {
            colHome.getColumn(i).setResizable(false);
        }
        
        tbDoiKhach.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel colAway = tbDoiKhach.getColumnModel();
        
        colAway.getColumn(0).setPreferredWidth(140); // Tên cầu thủ
        colAway.getColumn(1).setPreferredWidth(112); // Vị trí
        colAway.getColumn(2).setPreferredWidth(70); // Vai trò
        
        for (int i = 0; i < colAway.getColumnCount(); i++) {
            colAway.getColumn(i).setResizable(false);
        }
        
        loadData();
        
        getMatchStatus();
        setBtnVisibility();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        btnFM = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbTenDoiNha = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDoiNha = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnChonDoi = new javax.swing.JButton();
        btnChonCauThuDoiNha = new javax.swing.JButton();
        btnChonCauThuDoiKhach = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbTenDoiKhach = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDoiKhach = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(1, 0));

        panelHome.setBackground(new java.awt.Color(0, 76, 127));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setPreferredSize(new java.awt.Dimension(1000, 600));

        panelMenu.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu.setPreferredSize(new java.awt.Dimension(1000, 40));

        btnFM.setBackground(new java.awt.Color(0, 0, 0));
        btnFM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFM.setForeground(new java.awt.Color(255, 255, 255));
        btnFM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Artboard 2.png"))); // NOI18N
        btnFM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFM.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFMActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Untitled-3.png"))); // NOI18N
        btnBack.setMaximumSize(new java.awt.Dimension(60, 45));
        btnBack.setMinimumSize(new java.awt.Dimension(60, 45));
        btnBack.setPreferredSize(new java.awt.Dimension(60, 45));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFM)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFM, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(340, 400));

        lbTenDoiNha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTenDoiNha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTenDoiNha.setText("ĐỘI NHÀ");
        lbTenDoiNha.setMinimumSize(new java.awt.Dimension(105, 30));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(330, 360));

        tbDoiNha.setAutoCreateRowSorter(true);
        tbDoiNha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDoiNha);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTenDoiNha, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbTenDoiNha, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnChonDoi.setBackground(new java.awt.Color(0, 76, 127));
        btnChonDoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChonDoi.setForeground(new java.awt.Color(255, 255, 255));
        btnChonDoi.setText("CHỌN ĐỘI THAM GIA");
        btnChonDoi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnChonDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonDoiActionPerformed(evt);
            }
        });

        btnChonCauThuDoiNha.setBackground(new java.awt.Color(0, 76, 127));
        btnChonCauThuDoiNha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChonCauThuDoiNha.setForeground(new java.awt.Color(255, 255, 255));
        btnChonCauThuDoiNha.setText("CHỌN CẦU THỦ ĐỘI NHÀ");
        btnChonCauThuDoiNha.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnChonCauThuDoiNha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonCauThuDoiNhaActionPerformed(evt);
            }
        });

        btnChonCauThuDoiKhach.setBackground(new java.awt.Color(0, 76, 127));
        btnChonCauThuDoiKhach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChonCauThuDoiKhach.setForeground(new java.awt.Color(255, 255, 255));
        btnChonCauThuDoiKhach.setText("CHỌN CẦU THỦ ĐỘI KHÁCH");
        btnChonCauThuDoiKhach.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnChonCauThuDoiKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonCauThuDoiKhachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnChonCauThuDoiNha, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addComponent(btnChonCauThuDoiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnChonDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnChonDoi)
                .addGap(18, 18, 18)
                .addComponent(btnChonCauThuDoiNha)
                .addGap(18, 18, 18)
                .addComponent(btnChonCauThuDoiKhach)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(340, 400));

        lbTenDoiKhach.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTenDoiKhach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTenDoiKhach.setText("ĐỘI KHÁCH");
        lbTenDoiKhach.setPreferredSize(new java.awt.Dimension(135, 30));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(330, 360));

        tbDoiKhach.setAutoCreateRowSorter(true);
        tbDoiKhach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbDoiKhach);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTenDoiKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lbTenDoiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐỘI NHÀ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ĐỘI KHÁCH");

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelHomeLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        add(panelHome);
    }// </editor-fold>//GEN-END:initComponents
    
    private void deleteAllEvents(){
        try {
            MatchEventService service = new MatchEventService();
            service.deleteAllEventsOfMatch(matchId);
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void loadTableDoiNha(){
        try {
            MatchPlayerService service = new MatchPlayerService();
            PlayerService pService = new PlayerService();
            doiNha = service.getByMatchAndTeam(matchId, idDoiNha);
            modelDoiNha.setRowCount(0);
            if(doiNha.size() == 11){
                isSelectedPlayerHome = true;
                for(MatchPlayers mp : doiNha){
                    Player player = pService.getPlayerById(mp.getPlayerId());
                    String role = mp.getPlayerRole().equals(PlayerRole.STARTING) ? "Đá chính" : "Dự bị";
                    modelDoiNha.addRow(new Object[]{player.getPlayerName(), mp.getPosition().name(), role});
                }
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void loadTableDoiKhach(){
        try {
            MatchPlayerService service = new MatchPlayerService();
            PlayerService pService = new PlayerService();
            doiKhach = service.getByMatchAndTeam(matchId, idDoiKhach);
            modelDoiKhach.setRowCount(0);
            if(doiKhach.size() == 11){
                isSelectedPlayerAway = true;
                for(MatchPlayers mp : doiKhach){
                    Player player = pService.getPlayerById(mp.getPlayerId());
                    String role = mp.getPlayerRole().equals(PlayerRole.STARTING) ? "Đá chính" : "Dự bị";
                    modelDoiKhach.addRow(new Object[]{player.getPlayerName(), mp.getPosition().name(), role});
                }
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void loadData(){
        try {
            MatchTeamService mtService = new MatchTeamService();
            List<MatchTeams> mtLst = mtService.getTeamOfMatch(matchId);
            
            if(mtLst.size() < 2){
                isSelectedTeam = false;
                lbTenDoiNha.setText(CHUA_XAC_DINH);
                lbTenDoiKhach.setText(CHUA_XAC_DINH);
                return;
            }
            
            isSelectedTeam = true;
            
            for(MatchTeams mt : mtLst){
                if(mt.getTeamRole().equals(TeamRole.HOME)) idDoiNha = mt.getTeamId();
                if(mt.getTeamRole().equals(TeamRole.AWAY)) idDoiKhach = mt.getTeamId();
            }
            
            TeamService tService = new TeamService();
            String tenDoiNha = tService.getTeamById(idDoiNha).getTeamName();
            String tenDoiKhach = tService.getTeamById(idDoiKhach).getTeamName();
            
            lbTenDoiNha.setText(tenDoiNha);
            lbTenDoiKhach.setText(tenDoiKhach);
            
            loadTableDoiNha();
            loadTableDoiKhach();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void getMatchStatus(){
        try {
            MatchService service = new MatchService();
            isMatchFinish = service.isMatchFinished(matchId);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void setBtnVisibility(){
        btnChonDoi.setEnabled(!isMatchFinish);
        btnChonCauThuDoiNha.setEnabled(!isMatchFinish && isSelectedTeam);
        btnChonCauThuDoiKhach.setEnabled(!isMatchFinish && isSelectedTeam);
    }
    
    private void btnFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFMActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ScreenManager.get().clearHistory();
        if (mainFrame != null) {
            mainFrame.showHome();
        }
    }//GEN-LAST:event_btnFMActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ScreenManager.get().back();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnChonDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonDoiActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ChonDoiDialog dialog = new ChonDoiDialog(mainFrame, true, isSelectedTeam, idDoiNha, idDoiKhach);
        dialog.setVisible(true);
        
        if(!dialog.isConfirm()) return;
        
        try {
            MatchTeamService mtService = new MatchTeamService();
            MatchPlayerService mpService = new MatchPlayerService();
            TeamService service = new TeamService();
            int homeTeamId = dialog.getHomeTeamId();
            int awayTeamId = dialog.getAwayTeamId();
            if(!isSelectedTeam){
                mtService.addMatchTeam(new MatchTeams(matchId, homeTeamId, TeamRole.HOME));
                mtService.addMatchTeam(new MatchTeams(matchId, awayTeamId, TeamRole.AWAY));
            }
            else {
                
                mtService.deleteById(matchId, idDoiNha);
                mtService.deleteById(matchId, idDoiKhach);

                mtService.addMatchTeam(new MatchTeams(matchId, awayTeamId, TeamRole.AWAY));
                mtService.addMatchTeam(new MatchTeams(matchId, homeTeamId, TeamRole.HOME));
            }
            lbTenDoiNha.setText(service.getTeamById(homeTeamId).getTeamName());
            lbTenDoiKhach.setText(service.getTeamById(awayTeamId).getTeamName());
            if(isSelectedTeam){
                if(idDoiNha != homeTeamId) mpService.delete(doiNha);
                if(idDoiKhach != awayTeamId) mpService.delete(doiKhach);
            }
            idDoiNha = homeTeamId;
            idDoiKhach = awayTeamId;
            isSelectedTeam = true;
            loadTableDoiNha();
            loadTableDoiKhach();
            setBtnVisibility();
            deleteAllEvents();
        } catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnChonDoiActionPerformed

    private void btnChonCauThuDoiNhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonCauThuDoiNhaActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ChonDoiHinhDialog dialog = new ChonDoiHinhDialog(mainFrame, true, idDoiNha, isSelectedPlayerHome);
        dialog.setVisible(true);
        
        if(!dialog.isConfirm()) return;
        
        try{
            List<Player> daChinh = dialog.getStartingList();
            List<Player> duBi = dialog.getSubList();
            MatchPlayerService mpService = new MatchPlayerService();
            if(isSelectedPlayerHome){
                 mpService.delete(doiNha);
            }
            
            for(Player player : daChinh) mpService.add(new MatchPlayers(matchId, player.getPlayerId(), PlayerRole.STARTING, player.getPosition()));
            for(Player player : duBi) mpService.add(new MatchPlayers(matchId, player.getPlayerId(), PlayerRole.SUBSTITUTE, player.getPosition()));
            
            loadTableDoiNha();
            deleteAllEvents();
            
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnChonCauThuDoiNhaActionPerformed

    private void btnChonCauThuDoiKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonCauThuDoiKhachActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ChonDoiHinhDialog dialog = new ChonDoiHinhDialog(mainFrame, true, idDoiKhach, isSelectedPlayerAway);
        dialog.setVisible(true);
        
        if(!dialog.isConfirm()) return;
        
        try{
            List<Player> daChinh = dialog.getStartingList();
            List<Player> duBi = dialog.getSubList();
            MatchPlayerService mpService = new MatchPlayerService();
            if(isSelectedPlayerAway){
                 mpService.delete(doiKhach);
            }
            
            for(Player player : daChinh) mpService.add(new MatchPlayers(matchId, player.getPlayerId(), PlayerRole.STARTING, player.getPosition()));
            for(Player player : duBi) mpService.add(new MatchPlayers(matchId, player.getPlayerId(), PlayerRole.SUBSTITUTE, player.getPosition()));
            
            loadTableDoiKhach();
            deleteAllEvents();
            
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnChonCauThuDoiKhachActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChonCauThuDoiKhach;
    private javax.swing.JButton btnChonCauThuDoiNha;
    private javax.swing.JButton btnChonDoi;
    private javax.swing.JButton btnFM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbTenDoiKhach;
    private javax.swing.JLabel lbTenDoiNha;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JTable tbDoiKhach;
    private javax.swing.JTable tbDoiNha;
    // End of variables declaration//GEN-END:variables
}
