/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package N23DCCN058.fm.ui.panel;

import N23DCCN058.fm.exception.ServiceException;
import N23DCCN058.fm.exception.ValidationException;
import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.Team;
import N23DCCN058.fm.model.TeamStatistic;
import N23DCCN058.fm.service.StatisticService;
import N23DCCN058.fm.service.TeamService;
import N23DCCN058.fm.ui.dialog.SuaThongTinDoiDialog;
import N23DCCN058.fm.ui.dialog.ThemDoiDialog;
import N23DCCN058.fm.ui.dialog.TimDoiDialog;
import N23DCCN058.fm.ui.frame.MainFrame;
import N23DCCN058.fm.ui.frame.ScreenManager;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author admin
 */
public class DoiBongPanel extends javax.swing.JPanel {

    /**
     * Creates new form CauThuPanel
     */
    private DefaultTableModel model;
    
    public DoiBongPanel() {
        initComponents();
        setSize(1000,600);
        String[] columnNames = {"ID", "Tên đội bóng", "Phòng ban", "Huấn luyện viên"};
        model = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(model);
        
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel col = jTable1.getColumnModel();
        
        col.getColumn(0).setPreferredWidth(50); // Id 
        col.getColumn(1).setPreferredWidth(200); // Tên đội bóng
        col.getColumn(2).setPreferredWidth(190); // Phòng ban
        col.getColumn(3).setPreferredWidth(190);  // Huấn luyện viên
        
        for (int i = 0; i < col.getColumnCount(); i++) {
            col.getColumn(i).setResizable(false);
        }
        
        initTableSelectionListener();
        updateButtonVisibility();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnDanhSach = new javax.swing.JButton();
        btnSuaThongTin = new javax.swing.JButton();
        btnXoaDoi = new javax.swing.JButton();
        btnXemChiTiet = new javax.swing.JButton();
        btnTimDoi = new javax.swing.JButton();
        btnThongSo = new javax.swing.JButton();
        btnThemDoi = new javax.swing.JButton();
        panelMenu11 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        btnFM7 = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        panelHome.setBackground(new java.awt.Color(0, 76, 127));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setPreferredSize(new java.awt.Dimension(1000, 600));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(630, 460));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnDanhSach.setBackground(new java.awt.Color(0, 76, 127));
        btnDanhSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDanhSach.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSach.setText("DANH SÁCH ĐỘI BÓNG");
        btnDanhSach.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachActionPerformed(evt);
            }
        });

        btnSuaThongTin.setBackground(new java.awt.Color(0, 76, 127));
        btnSuaThongTin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaThongTin.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaThongTin.setText("SỬA THÔNG TIN");
        btnSuaThongTin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThongTinActionPerformed(evt);
            }
        });

        btnXoaDoi.setBackground(new java.awt.Color(0, 76, 127));
        btnXoaDoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaDoi.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaDoi.setText("XÓA ĐỘI");
        btnXoaDoi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnXoaDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDoiActionPerformed(evt);
            }
        });

        btnXemChiTiet.setBackground(new java.awt.Color(0, 76, 127));
        btnXemChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXemChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnXemChiTiet.setText("XEM CHI TIẾT ĐỘI");
        btnXemChiTiet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        btnTimDoi.setBackground(new java.awt.Color(0, 76, 127));
        btnTimDoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimDoi.setForeground(new java.awt.Color(255, 255, 255));
        btnTimDoi.setText("TÌM ĐỘI");
        btnTimDoi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnTimDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimDoiActionPerformed(evt);
            }
        });

        btnThongSo.setBackground(new java.awt.Color(0, 76, 127));
        btnThongSo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongSo.setForeground(new java.awt.Color(242, 242, 242));
        btnThongSo.setText("XEM THÔNG SỐ");
        btnThongSo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnThongSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongSoActionPerformed(evt);
            }
        });

        btnThemDoi.setBackground(new java.awt.Color(0, 76, 127));
        btnThemDoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemDoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDoi.setText("THÊM ĐỘI MỚI");
        btnThemDoi.setToolTipText("");
        btnThemDoi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnThemDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThemDoi, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(btnDanhSach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaThongTin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXemChiTiet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimDoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(btnXoaDoi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongSo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnDanhSach)
                .addGap(18, 18, 18)
                .addComponent(btnThemDoi)
                .addGap(18, 18, 18)
                .addComponent(btnTimDoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnThongSo)
                .addGap(18, 18, 18)
                .addComponent(btnSuaThongTin)
                .addGap(18, 18, 18)
                .addComponent(btnXemChiTiet)
                .addGap(18, 18, 18)
                .addComponent(btnXoaDoi)
                .addGap(16, 16, 16))
        );

        panelMenu11.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu11.setPreferredSize(new java.awt.Dimension(1000, 40));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Untitled-3.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnFM7.setBackground(new java.awt.Color(0, 0, 0));
        btnFM7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFM7.setForeground(new java.awt.Color(255, 255, 255));
        btnFM7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Artboard 2.png"))); // NOI18N
        btnFM7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFM7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFM7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFM7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu11Layout = new javax.swing.GroupLayout(panelMenu11);
        panelMenu11.setLayout(panelMenu11Layout);
        panelMenu11Layout.setHorizontalGroup(
            panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFM7)
                .addContainerGap())
        );
        panelMenu11Layout.setVerticalGroup(
            panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFM7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addComponent(panelMenu11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(panelMenu11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );

        add(panelHome);
    }// </editor-fold>//GEN-END:initComponents

    private void initTableSelectionListener(){
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { // Đảm bảo chỉ xử lý khi chọn xong
                updateButtonVisibility();
            }   
        }); 
    }
    
    
    
    private void updateButtonVisibility() {
        int selectedCount = jTable1.getSelectedRowCount();

                // Nếu chưa chọn hoặc chọn > 1 dòng -> disable nút
        boolean enable = (selectedCount == 1);
        btnThongSo.setEnabled(enable);
        btnSuaThongTin.setEnabled(enable);
        btnXoaDoi.setEnabled(enable);
        btnXemChiTiet.setEnabled(enable);
    }
    
    private void resetTableData(){
        model.setRowCount(0);
    }
    
    private void hienDanhSach(){
        TeamService tService = new TeamService();
        try {
            List<Team>list = tService.getAllTeam();
            hienDanhSach(list);
        } catch (ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Không thể lấy dữ liệu!", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    
    
    private void hienDanhSach(List<Team> list){
        resetTableData();
        for(Team team : list) model.addRow(team.toObjectArray());

        model.fireTableDataChanged();
        jTable1.revalidate();
        jTable1.repaint();
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }
    
    private void btnDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachActionPerformed
        hienDanhSach();
    }//GEN-LAST:event_btnDanhSachActionPerformed

    private void btnTimDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimDoiActionPerformed

        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        TimDoiDialog dialog = new TimDoiDialog(mainFrame, true);
        //dialog.setVisible(true);
        if (mainFrame != null) {
        // Tạo GlassPane làm mờ
            final javax.swing.JPanel glassPane = new javax.swing.JPanel() {
            @Override
                protected void paintComponent(java.awt.Graphics g) {
                    super.paintComponent(g);
                // Vẽ lớp phủ màu đen trong suốt
                    g.setColor(new java.awt.Color(0, 0, 0, 128)); // 128 = 50% opacity
                    g.fillRect(0, 0, getWidth(), getHeight());
                }
            };
        
        glassPane.setOpaque(false);
        // Chặn tương tác với các component bên dưới
        glassPane.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                dialog.dispose();// Click vào vùng mờ sẽ đóng dialog
            }
        });
        
        // Đặt glassPane
        mainFrame.setGlassPane(glassPane);
        glassPane.setVisible(true);
        
        // Hiển thị dialog
        
        
        // Thêm listener để tắt glassPane khi đóng dialog
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                glassPane.setVisible(false);
            }
        });
        
        
        dialog.setVisible(true);
    }
        
        if(!dialog.isConfirm()) return;
        
        try {
            TeamService tService = new TeamService();
            Team newTeam = dialog.getTeam();
            List<Team> list = tService.searchTeam(newTeam);
            hienDanhSach(list);
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimDoiActionPerformed

    private void btnXoaDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDoiActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa đội bóng này không?\n Xóa đội bóng sẽ xóa toàn bộ cầu thủ và thông tin liên quan đến đội!",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );   
        if(choice != JOptionPane.YES_OPTION) return;
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 đội bóng để xóa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        try {
            TeamService tService = new TeamService();
            tService.deleteTeamById(id);
            hienDanhSach();
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaDoiActionPerformed

    private void btnThemDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDoiActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ThemDoiDialog dialog = new ThemDoiDialog(mainFrame, true);
        //dialog.setVisible(true);
        if (mainFrame != null) {
        // Tạo GlassPane làm mờ
            final javax.swing.JPanel glassPane = new javax.swing.JPanel() {
            @Override
                protected void paintComponent(java.awt.Graphics g) {
                    super.paintComponent(g);
                // Vẽ lớp phủ màu đen trong suốt
                    g.setColor(new java.awt.Color(0, 0, 0, 128)); // 128 = 50% opacity
                    g.fillRect(0, 0, getWidth(), getHeight());
                }
            };
        
            glassPane.setOpaque(false);
            // Chặn tương tác với các component bên dưới
            glassPane.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent e) {
                    dialog.dispose();// Click vào vùng mờ sẽ đóng dialog
                }
            });

            // Đặt glassPane
            mainFrame.setGlassPane(glassPane);
            glassPane.setVisible(true);

            // Hiển thị dialog


            // Thêm listener để tắt glassPane khi đóng dialog
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    glassPane.setVisible(false);
                }
            });


            dialog.setVisible(true);
        }
        
        
        if(!dialog.isConfirm()) return;
        
        try {
            TeamService tService = new TeamService();
            Team newTeam = dialog.getTeam();
            tService.addTeam(newTeam);
            
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
        hienDanhSach();
    }//GEN-LAST:event_btnThemDoiActionPerformed

    private void btnFM7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFM7ActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ScreenManager.get().clearHistory();
        if (mainFrame != null) {
            mainFrame.showHome();
        }
    }//GEN-LAST:event_btnFM7ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        resetTableData();
        ScreenManager.get().back();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThongTinActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 đội bóng để sửa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        String name = jTable1.getValueAt(selectedRow, 1).toString();
        String department = jTable1.getValueAt(selectedRow, 2).toString();
        String coach = jTable1.getValueAt(selectedRow, 3).toString();
        
        Team selectedTeam = new Team(id, name, department, coach);
        
        SuaThongTinDoiDialog dialog = new SuaThongTinDoiDialog(mainFrame, true, selectedTeam);
        dialog.setVisible(true);
        
        if(!dialog.isConfirm()) return;
        
        try {
            TeamService tService = new TeamService();
            Team newTeam = dialog.getTeam();
            tService.updateTeam(newTeam);
            hienDanhSach();
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaThongTinActionPerformed

    private void btnThongSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongSoActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 đội bóng để sửa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        
        try {
            StatisticService ss = new StatisticService();
            TeamService tService = new TeamService();
            Team team = tService.getTeamById(id);
            TeamStatistic ts = ss.getTeamStatistic(id);
            String info = "Tên đội bóng : " + team.getTeamName() + "\n" 
                        + "Khoa: " + team.getDepartment() + "\n"
                        + "Huấn luyện viên: " + team.getCoachName() + "\n"
                        + "Số lượng cầu thủ thuộc đội: " + ts.getNumOfPlayers() + "\n"
                        + "Tổng số trận đã chơi: " + ts.getNumOfPLayedMatches() + "\n"
                        + "Số trận thắng: " + ts.getNumOfWinMatches() + "\n"
                        + "Số trận hòa: " + ts.getNumOfDrawMatches() + "\n"
                        + "Số trận thua: " + ts.getNumOfLoseMatches() + "\n"
                        + "Tổng số bàn đã ghi: " + ts.getNumOfGoals() + "\n"
                        + "Xếp hạng: " + ts.getRank() + "\n"
                        + "Tổng điểm: " + ts.getTotalPoints();
            JOptionPane.showMessageDialog(this, info, "Thông số đội" , JOptionPane.INFORMATION_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThongSoActionPerformed

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        CauThuPanel cauThuPanel = mainFrame.getCauThuPanel();
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 đội bóng để sửa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        
        cauThuPanel.showPlayerOfTeam(id);
        ScreenManager.get().show(MainFrame.CARD_CAUTHU);
       
    }//GEN-LAST:event_btnXemChiTietActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSach;
    private javax.swing.JButton btnFM7;
    private javax.swing.JButton btnSuaThongTin;
    private javax.swing.JButton btnThemDoi;
    private javax.swing.JButton btnThongSo;
    private javax.swing.JButton btnTimDoi;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JButton btnXoaDoi;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu11;
    // End of variables declaration//GEN-END:variables
}
