/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package N23DCCN058.fm.ui.panel;

import N23DCCN058.fm.model.Match;
import N23DCCN058.fm.model.MatchStatus;
import N23DCCN058.fm.model.Referee;
import N23DCCN058.fm.service.MatchEventService;
import N23DCCN058.fm.service.MatchService;
import N23DCCN058.fm.service.RefereeService;
import N23DCCN058.fm.ui.frame.MainFrame;
import N23DCCN058.fm.ui.frame.ScreenManager;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author admin
 */
public class GhiSuKienPanel_ChonTranDau extends javax.swing.JPanel {

    /**
     * Creates new form GhiSukienPanel_1
     */
    private List<Match> list;
    private DefaultTableModel model;
    
    public GhiSuKienPanel_ChonTranDau() {
        initComponents();
        setSize(1000,600);
        initList();
        initTable();
        initTableData();
        initTableSelectionListener();
        btnChon.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhSach = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        btnChon = new javax.swing.JButton();
        panelMenu13 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        btnFM9 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(0, 76, 127));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setPreferredSize(new java.awt.Dimension(1000, 600));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(630, 460));

        tbDanhSach.setAutoCreateRowSorter(true);
        tbDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbDanhSach);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnChon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnChon.setForeground(new java.awt.Color(0, 76, 127));
        btnChon.setText("CHỌN");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        panelMenu13.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu13.setPreferredSize(new java.awt.Dimension(1000, 40));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Untitled-3.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnFM9.setBackground(new java.awt.Color(0, 0, 0));
        btnFM9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFM9.setForeground(new java.awt.Color(255, 255, 255));
        btnFM9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Artboard 2.png"))); // NOI18N
        btnFM9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFM9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFM9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFM9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu13Layout = new javax.swing.GroupLayout(panelMenu13);
        panelMenu13.setLayout(panelMenu13Layout);
        panelMenu13Layout.setHorizontalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFM9)
                .addContainerGap())
        );
        panelMenu13Layout.setVerticalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFM9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(panelMenu13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(panelMenu13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnChon))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        add(panelHome, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void initTableSelectionListener(){
        tbDanhSach.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { // Đảm bảo chỉ xử lý khi chọn xong
                int selectedCount = tbDanhSach.getSelectedRowCount();

                // Nếu chưa chọn hoặc chọn > 1 dòng -> disable nút
                boolean enable = (selectedCount == 1);
                btnChon.setEnabled(enable);
            }   
        }); 
    }
    
    private void initTable(){
        String[] columnNames = {"ID", "Trọng tài", "Ngày diễn ra", "Trạng thái"};
        model = new DefaultTableModel(columnNames, 0);
        tbDanhSach.setModel(model);
        
        tbDanhSach.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel col = tbDanhSach.getColumnModel();
        
        col.getColumn(0).setPreferredWidth(50); // Id 
        col.getColumn(1).setPreferredWidth(250); // Trọng tài
        col.getColumn(2).setPreferredWidth(150); // Ngày diễn ra
        col.getColumn(3).setPreferredWidth(200);  // Trạng thái
        
        for (int i = 0; i < col.getColumnCount(); i++) {
            col.getColumn(i).setResizable(false);
        }
    }
    
    private void initTableData(){
        try {
            RefereeService service = new RefereeService();
            Map<Integer,Referee> map = service.getAllReferee().stream()
                    .collect(Collectors.toMap(referee -> referee.getRefereeId(), referee -> referee));
            MatchService mtService = new MatchService();
            for(Match match: list){
                if(!mtService.isReady(match.getMatchId()))
                    continue;
                String status = match.getMatchStatus().equals(MatchStatus.DA_DIEN_RA) ? "Đã diễn ra" : "Chưa diễn ra";
                model.addRow(new Object[]{match.getMatchId(), map.get(match.getRefereeId()), match.getMatchDate(), status});
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void initList(){
        try{
            MatchService service = new MatchService();
            list = service.getAllMatch();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = tbDanhSach.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 trận đấu bóng để xóa!");
            return;
        }
        
        int id = (int) tbDanhSach.getValueAt(selectedRow, 0);
        mainFrame.showGhiSuKien(id);
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnFM9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFM9ActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ScreenManager.get().clearHistory();
        if (mainFrame != null) {
            mainFrame.showHome();
        }
    }//GEN-LAST:event_btnFM9ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ScreenManager.get().back();
    }//GEN-LAST:event_jButton9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnFM9;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu13;
    private javax.swing.JTable tbDanhSach;
    // End of variables declaration//GEN-END:variables
}
