package N23DCCN058.fm.ui.panel;

import N23DCCN058.fm.model.EventType;
import N23DCCN058.fm.model.MatchEvents;
import N23DCCN058.fm.model.MatchPlayers;
import N23DCCN058.fm.model.MatchTeams;
import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.PlayerPosition;
import N23DCCN058.fm.model.PlayerRole;
import N23DCCN058.fm.model.Team;
import N23DCCN058.fm.model.TeamRole;
import N23DCCN058.fm.service.MatchEventService;
import N23DCCN058.fm.service.MatchPlayerService;
import N23DCCN058.fm.service.MatchTeamService;
import N23DCCN058.fm.service.PlayerService;
import N23DCCN058.fm.service.TeamService;
import N23DCCN058.fm.ui.dialog.ThemSuKienDialog;
import N23DCCN058.fm.ui.frame.MainFrame;
import N23DCCN058.fm.ui.frame.ScreenManager;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author admin
 */
public class GhiSuKienPanel extends javax.swing.JPanel {

    /**
     * Creates new form GhiSuKienPanel_2
     */
    private int matchId, lastEventTime;
    private Team home, away;
    private List<MatchPlayers> doiNha, doiKhach;
    private Map<Integer, PlayerPosition> positions;
    private Map<Integer, Player> playerHome, playerAway, players;
    private Set<Integer> homePlayerOnField, awayPlayerOnField, playerGetYellowCard, playerGetRedCard;
    private List<MatchEvents> events;
    private boolean isStart, isFinish;
    private DefaultTableModel model;
    
    public GhiSuKienPanel(int matchId){
        initComponents();
        setSize(1000,600);
        this.matchId = matchId;
        isStart = false;
        isFinish = false;
        doiNha = new ArrayList<>();
        doiKhach = new ArrayList<>();
        playerHome = new HashMap<>();
        playerAway = new HashMap<>();
        homePlayerOnField = new HashSet<>();
        awayPlayerOnField = new HashSet<>();
        playerGetYellowCard = new HashSet<>();
        playerGetRedCard = new HashSet<>();
        players = new HashMap<>();
        positions = new HashMap<>();
        
        String[] columnNames = {"ID", "Tên cầu thủ","Vị trí",  "Tên đội", "Loại sự liện", "Phút"};
        model = new DefaultTableModel(columnNames, 0);
        tbSuKien.setModel(model);
        
        tbSuKien.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel col = tbSuKien.getColumnModel();
        
        col.getColumn(0).setPreferredWidth(20); // Id 
        col.getColumn(1).setPreferredWidth(165); // Tên cầu thủ
        col.getColumn(2).setPreferredWidth(100); // Vị trí
        col.getColumn(3).setPreferredWidth(165);  // Tên đội
        col.getColumn(4).setPreferredWidth(140);  // Loại sự liện
        col.getColumn(5).setPreferredWidth(50); // Thời gian xảy ra
        
        for (int i = 0; i < col.getColumnCount(); i++) {
            col.getColumn(i).setResizable(false);
        }
        
        getTeam();
        initPosition();
        getPlayer();
        getEvent();
        updateAllButtonVisibility();
        showEventList();
        calculatePlayerOnField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu11 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        btnFM7 = new javax.swing.JButton();
        panelHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSuKien = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnBatDau = new javax.swing.JButton();
        btnKetThuc = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXoaTatCa = new javax.swing.JButton();
        panelMenu12 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        btnFM8 = new javax.swing.JButton();

        panelMenu11.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu11.setPreferredSize(new java.awt.Dimension(1000, 40));

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Untitled-3.png"))); // NOI18N

        btnFM7.setBackground(new java.awt.Color(153, 153, 153));
        btnFM7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFM7.setForeground(new java.awt.Color(255, 255, 255));
        btnFM7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Artboard 2.png"))); // NOI18N
        btnFM7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFM7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFM7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFM7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu11Layout = new javax.swing.GroupLayout(panelMenu11);
        panelMenu11.setLayout(panelMenu11Layout);
        panelMenu11Layout.setHorizontalGroup(
            panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFM7)
                .addContainerGap())
        );
        panelMenu11Layout.setVerticalGroup(
            panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFM7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(0, 76, 127));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setPreferredSize(new java.awt.Dimension(1000, 600));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(630, 460));

        tbSuKien.setAutoCreateRowSorter(true);
        tbSuKien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbSuKien);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnBatDau.setBackground(new java.awt.Color(0, 76, 127));
        btnBatDau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBatDau.setForeground(new java.awt.Color(255, 255, 255));
        btnBatDau.setText("BẮT ĐẦU TRẬN ĐẤU");
        btnBatDau.setToolTipText("");
        btnBatDau.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnBatDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatDauActionPerformed(evt);
            }
        });

        btnKetThuc.setBackground(new java.awt.Color(0, 76, 127));
        btnKetThuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKetThuc.setForeground(new java.awt.Color(255, 255, 255));
        btnKetThuc.setText("KẾT THÚC TRẬN ĐẤU");
        btnKetThuc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnKetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(0, 76, 127));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("THÊM SỰ KIỆN");
        btnThem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(0, 76, 127));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("XÓA SỰ KIỆN VỪA THÊM");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnXoaTatCa.setBackground(new java.awt.Color(0, 76, 127));
        btnXoaTatCa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaTatCa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTatCa.setText("XÓA TẤT CẢ");
        btnXoaTatCa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTatCaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaTatCa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnBatDau)
                .addGap(18, 18, 18)
                .addComponent(btnKetThuc)
                .addGap(18, 18, 18)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addGap(18, 18, 18)
                .addComponent(btnXoaTatCa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu12.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu12.setPreferredSize(new java.awt.Dimension(1000, 40));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Untitled-3.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        btnFM8.setBackground(new java.awt.Color(0, 0, 0));
        btnFM8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFM8.setForeground(new java.awt.Color(255, 255, 255));
        btnFM8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Artboard 2.png"))); // NOI18N
        btnFM8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFM8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFM8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFM8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu12Layout = new javax.swing.GroupLayout(panelMenu12);
        panelMenu12.setLayout(panelMenu12Layout);
        panelMenu12Layout.setHorizontalGroup(
            panelMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFM8)
                .addContainerGap())
        );
        panelMenu12Layout.setVerticalGroup(
            panelMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFM8, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addComponent(panelMenu12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(panelMenu12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addGap(32, 32, 32))
        );

        add(panelHome, "card2");
    }// </editor-fold>//GEN-END:initComponents
    private void initPosition(){
        try {
            MatchPlayerService service = new MatchPlayerService();
            List<MatchPlayers> plHome = service.getByMatchAndTeam(matchId, home.getTeamId());
            List<MatchPlayers> plAway = service.getByMatchAndTeam(matchId, away.getTeamId());

            for(MatchPlayers mp : plHome )
                positions.put(mp.getPlayerId(), mp.getPosition());

            for(MatchPlayers mp : plAway )
                positions.put(mp.getPlayerId(), mp.getPosition());
        } catch(Exception e){
            e.printStackTrace();
        }
     }
    
    private void updatePlayerOnField(MatchEvents event){
        lastEventTime = event.getEventTime();
        
        int id = event.getPlayerId();
        
        if(event.getEventType().equals(EventType.YELLOW_CARD)){
            if(playerGetYellowCard.contains(id)){
                playerGetYellowCard.remove((Object)id);
                playerGetRedCard.add(id);
                removeFromField(id);
            }
            else 
                playerGetYellowCard.add(id);
        }
        
        if(event.getEventType().equals(EventType.RED_CARD)){
            removeFromField(id);
            playerGetRedCard.add(id);
        }
        
        if(event.getEventType().equals(EventType.SUBSTITUTION_OUT)){
            removeFromField(id);
        }
        
        if(event.getEventType().equals(EventType.SUBSTITUTION_IN)){
            addToField(id);
        }
    }
    
    private void removeFromField(int id){
        if(homePlayerOnField.contains(id)) homePlayerOnField.remove((Object) id);
        else awayPlayerOnField.remove((Object) id);
    }
    
    private void addToField(int id){
        if(playerHome.containsKey(id)) homePlayerOnField.add(id);
        else awayPlayerOnField.add(id);
    }
    
    private void calculatePlayerOnField(){
        homePlayerOnField.clear();
        awayPlayerOnField.clear();
        playerGetYellowCard.clear();
        playerGetRedCard.clear();
        
        getPlayer();
        
        for(MatchPlayers mp : doiNha){
            if(mp.getPlayerRole().equals(PlayerRole.STARTING)) homePlayerOnField.add(mp.getPlayerId());
        }
        
        for(MatchPlayers mp : doiKhach){
            if(mp.getPlayerRole().equals(PlayerRole.STARTING)) awayPlayerOnField.add(mp.getPlayerId());
        }
        
        for(MatchEvents event : events){
            if(event.getPlayerId() == null) continue;
            updatePlayerOnField(event);
        }
    }
    
    private void showEventList(){
        getEvent();
        model.setRowCount(0);
        for(MatchEvents event : events){
            if(event.getPlayerId() == null){
                model.addRow(new Object[]{event.getEventId(), "", "", "", event.getEventType().getVietnamese(), event.getEventTime()});
                continue;
            }
            Player player;
            String teamName;
            if(playerHome.containsKey(event.getPlayerId())){
                player = playerHome.get(event.getPlayerId());
                teamName = home.getTeamName();
            }
            else {
                player = playerAway.get(event.getPlayerId());
                teamName = away.getTeamName();
            }
            
            model.addRow(new Object[]{event.getEventId(),player.getPlayerName(),positions.get(player.getPlayerId()).name(), teamName, event.getEventType().getVietnamese(), event.getEventTime()});
        }
    }
    
    private void updateButtonVisibility(){
        int selectedCount = tbSuKien.getSelectedRowCount();
        
        boolean enable = (selectedCount == 1);
        btnThem.setEnabled(isStart && !isFinish);
        btnXoa.setEnabled(!events.isEmpty() && isStart && !isFinish);
        btnXoaTatCa.setEnabled(!events.isEmpty() && isStart && !isFinish);
    }
    
    private void updateAllButtonVisibility(){
        if(!isStart && !isFinish){
            btnBatDau.setEnabled(true);
            btnKetThuc.setEnabled(false);
        }
        
        if(isStart && !isFinish){
            btnBatDau.setEnabled(false);
            btnKetThuc.setEnabled(true);
        }
        
        if(isStart && isFinish){
            btnBatDau.setEnabled(false);
            btnKetThuc.setEnabled(false);
        }
        
        if(!isStart || isFinish){
            btnThem.setEnabled(false);
            btnXoa.setEnabled(false);
            btnXoaTatCa.setEnabled(false);
        }
        
        updateButtonVisibility();
    }
    
    private void getTeam(){
        try {
            MatchTeamService mtService = new MatchTeamService();
            List<MatchTeams> mtLst = mtService.getTeamOfMatch(matchId);
            
            TeamService tService = new TeamService();
            for(MatchTeams mt : mtLst){
                if(mt.getTeamRole().equals(TeamRole.HOME)) home = tService.getTeamById(mt.getTeamId());
                if(mt.getTeamRole().equals(TeamRole.AWAY)) away = tService.getTeamById(mt.getTeamId());
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void getPlayer(){
        playerHome.clear();
        playerAway.clear();
        players.clear();
        try {
            MatchPlayerService service = new MatchPlayerService();
            doiNha = service.getByMatchAndTeam(matchId, home.getTeamId());
            doiKhach = service.getByMatchAndTeam(matchId, away.getTeamId());
            
            PlayerService pService = new PlayerService();
            for(MatchPlayers mp : doiNha){
                playerHome.put(mp.getPlayerId(), pService.getPlayerById(mp.getPlayerId()));
                players.put(mp.getPlayerId(), pService.getPlayerById(mp.getPlayerId()));
            }
                
            for(MatchPlayers mp : doiKhach){
                playerAway.put(mp.getPlayerId(), pService.getPlayerById(mp.getPlayerId()));
                players.put(mp.getPlayerId(), pService.getPlayerById(mp.getPlayerId()));
            }
                
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void getEvent(){
        try {
            MatchEventService service = new MatchEventService();
            events = service.getAllEventOfMatch(matchId);
            isStart = false;
            isFinish = false;
            if(!events.isEmpty()){
                if(events.getFirst().getEventType().equals(EventType.MATCH_START)) isStart = true;
                if(events.getLast().getEventType().equals(EventType.MATCH_END)) isFinish = true;
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);

        if(events.isEmpty()){
            JOptionPane.showMessageDialog(this, "Chưa có sự kiện để xóa!");
            return;
        }
        
        MatchEvents latest = events.getLast();
        MatchEvents preLatest = null;
        if(latest.getEventType().equals(EventType.SUBSTITUTION_IN)) preLatest = events.get(events.size() - 2);
        
        try {
            MatchEventService service = new MatchEventService();
            String message;
            if(latest.getEventType().equals(EventType.MATCH_START)) message = "Sự kiện bắt đầu trận đấu sẽ được xóa!\n Xác nhận xóa ?";
            else {
                String playerName;
                if(playerHome.containsKey(latest.getPlayerId())) playerName = playerHome.get(latest.getPlayerId()).getPlayerName();
                else playerName = playerAway.get(latest.getPlayerId()).getPlayerName();
                String info = "Tên cầu thủ: " + playerName + "| Loại sự kiện: " + latest.getEventType().getVietnamese() + "| Thời gian : " + latest.getEventTime();
                if(latest.getEventType().equals(EventType.SUBSTITUTION_IN)){
                    String name;
                    if(playerHome.containsKey(preLatest.getPlayerId())) name = playerHome.get(preLatest.getPlayerId()).getPlayerName();
                    else name = playerAway.get(preLatest.getPlayerId()).getPlayerName();
                    info += "\nTên cầu thủ: " + name + "| Loại sự kiện: " + preLatest.getEventType().getVietnamese() + "| Thời gian : " + preLatest.getEventTime();
                }
                message = "Sự kiện sẽ bị xóa: \n" + info + "\nXác nhận xóa ?";
            }
            int choice = JOptionPane.showConfirmDialog(
                this,
                message,
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if(choice == JOptionPane.YES_OPTION){
                
                service.deleteEventById(latest.getEventId());
                if(latest.getEventType().equals(EventType.SUBSTITUTION_IN))
                    service.deleteEventById(preLatest.getEventId());
                
                lastEventTime = events.isEmpty() ? 0 : events.getLast().getEventTime();
                isStart = !events.isEmpty();
            
                
                showEventList();
                calculatePlayerOnField();
                updateAllButtonVisibility();
            }
            
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnXoaTatCaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTatCaActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        try {
            int choice = JOptionPane.showConfirmDialog(
                this,
                "Toàn bộ danh sách sự kiện sẽ bị xóa!",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if(choice == JOptionPane.YES_OPTION){
                
                MatchEventService service = new MatchEventService();
                service.deleteAllEventsOfMatch(matchId);
                events.clear();
                
                lastEventTime = 0;
                isStart = false;
                
                calculatePlayerOnField();
                showEventList();
                updateAllButtonVisibility();
            }
            
        } catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnXoaTatCaActionPerformed

    private void btnFM7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFM7ActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        if (mainFrame != null) {
            mainFrame.showHome();
        }
    }//GEN-LAST:event_btnFM7ActionPerformed

    private void btnFM8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFM8ActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ScreenManager.get().clearHistory();
        if (mainFrame != null) {
            mainFrame.showHome();
        }
    }//GEN-LAST:event_btnFM8ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        ScreenManager.get().back();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauActionPerformed
        try {
            isStart = true;
            MatchEvents event = new MatchEvents(matchId, null, EventType.MATCH_START, 0);
            
            MatchEventService service = new MatchEventService();
            service.startMatch(matchId);

            
            
            showEventList();
            updateAllButtonVisibility();
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBatDauActionPerformed

    private void btnKetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucActionPerformed
        
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Sau khi kết thúc trận đấu các sự kiện sẽ không được thay đổi!\n Vẫn kết thúc trận ?",
            "Xác nhận",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        if(choice != JOptionPane.YES_OPTION){
            return;
        }
        
        try {
            isFinish = true;
            
            MatchEventService service = new MatchEventService();
            service.endMatch(matchId);
            showEventList();
            updateAllButtonVisibility();
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnKetThucActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ThemSuKienDialog dialog = new ThemSuKienDialog(mainFrame, true, matchId, home, away, playerHome, playerAway, homePlayerOnField, awayPlayerOnField,playerGetRedCard,positions, lastEventTime);
        dialog.setVisible(true);
        
        if(!dialog.isConfirm()) return;
        
        try {
            MatchEvents event = dialog.getEvent();
            MatchEventService service = new MatchEventService();
            service.addEvent(event);
            updatePlayerOnField(event);
            if(event.getEventType().equals(EventType.SUBSTITUTION_OUT)){
                MatchEvents additionEvent = dialog.getSubtitutionIn();
                service.addEvent(additionEvent);
                updatePlayerOnField(additionEvent);
            }
            showEventList();
            updateButtonVisibility();
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatDau;
    private javax.swing.JButton btnFM7;
    private javax.swing.JButton btnFM8;
    private javax.swing.JButton btnKetThuc;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTatCa;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu11;
    private javax.swing.JPanel panelMenu12;
    private javax.swing.JTable tbSuKien;
    // End of variables declaration//GEN-END:variables
}
