/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package N23DCCN058.fm.ui.panel;

import N23DCCN058.fm.exception.ServiceException;
import N23DCCN058.fm.service.TournamentService;
import N23DCCN058.fm.ui.frame.MainFrame;
import N23DCCN058.fm.ui.frame.ScreenManager;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author admin
 */
public class HomePanel extends javax.swing.JPanel {
    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(1000, 600)); // Thay vì setSize   
        setBtn();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        panelHome = new javax.swing.JPanel();
        btnTaoGiaiDau = new javax.swing.JButton();
        btnTiepTucGiaiDau = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setMinimumSize(new java.awt.Dimension(1000, 600));
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new java.awt.GridLayout(1, 0));

        panelHome.setBackground(new java.awt.Color(0, 76, 127));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setPreferredSize(new java.awt.Dimension(1000, 600));

        btnTaoGiaiDau.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTaoGiaiDau.setForeground(new java.awt.Color(0, 76, 127));
        btnTaoGiaiDau.setText("TẠO GIẢI ĐẤU MỚI");
        btnTaoGiaiDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoGiaiDauActionPerformed(evt);
            }
        });

        btnTiepTucGiaiDau.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnTiepTucGiaiDau.setForeground(new java.awt.Color(0, 76, 127));
        btnTiepTucGiaiDau.setText("TIẾP TỤC GIẢI ĐẤU");
        btnTiepTucGiaiDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTiepTucGiaiDauActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FOOTBALL");

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MANAGER");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/pictures/v1.png"))); // NOI18N

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addContainerGap(71, Short.MAX_VALUE)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(80, 80, 80))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTiepTucGiaiDau)
                            .addComponent(btnTaoGiaiDau, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel4))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(116, 116, 116)
                .addComponent(btnTaoGiaiDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(49, 49, 49)
                .addComponent(btnTiepTucGiaiDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
        );

        add(panelHome);
    }// </editor-fold>//GEN-END:initComponents


    
    public void setBtn(){
        if(!MainFrame.isTournamentCreated()) btnTiepTucGiaiDau.setVisible(false);
        else btnTiepTucGiaiDau.setVisible(true);
    }
            
    private void btnTiepTucGiaiDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTiepTucGiaiDauActionPerformed
        ScreenManager.get().show(MainFrame.CARD_TONGQUAN);
    }//GEN-LAST:event_btnTiepTucGiaiDauActionPerformed

    private void btnTaoGiaiDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoGiaiDauActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        if(!MainFrame.isTournamentCreated()) mainFrame.showTaoGiai();
        else {
            int result = JOptionPane.showConfirmDialog(this
                    , "Tạo giải đấu mới sẽ xóa toàn bộ dữ liệu của giải đấu hiện tại. Tiếp tục tạo giải đấu mới ?"
                    ,"Xác nhận"
                    ,JOptionPane.YES_NO_CANCEL_OPTION
                    , JOptionPane.QUESTION_MESSAGE);
            if(result == JOptionPane.YES_OPTION){
                mainFrame.showTaoGiai();
            }
        }
    }//GEN-LAST:event_btnTaoGiaiDauActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaoGiaiDau;
    private javax.swing.JButton btnTiepTucGiaiDau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelHome;
    // End of variables declaration//GEN-END:variables
}
