package N23DCCN058.fm.ui.panel;

import N23DCCN058.fm.model.FinishedMatchDetails;
import N23DCCN058.fm.model.MatchEvents;
import N23DCCN058.fm.model.MatchPlayers;
import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.PlayerRole;
import N23DCCN058.fm.model.Team;
import N23DCCN058.fm.service.FinishedMatchDetailsService;
import N23DCCN058.fm.service.MatchEventService;
import N23DCCN058.fm.service.MatchPlayerService;
import N23DCCN058.fm.service.PlayerService;
import N23DCCN058.fm.service.RefereeService;
import N23DCCN058.fm.service.TeamService;
import N23DCCN058.fm.ui.frame.MainFrame;
import N23DCCN058.fm.ui.frame.ScreenManager;
import java.util.List;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author admin
 */
public class KetQuaTranDauPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChiTietTranDauPanel
     */
    private int matchId;
    private FinishedMatchDetails details;
    private DefaultTableModel modelDoiNha, modelDoiKhach;
    
    public KetQuaTranDauPanel(int matchId) {
        initComponents();
        this.matchId = matchId;
        setLableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        panelHome = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnDoiHinhRaSan = new javax.swing.JButton();
        btnSuKien = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        panelMenu13 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        btnFM9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbTenDoiNha = new javax.swing.JLabel();
        lbTenDoiKhach = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbBanThangDoiNha = new javax.swing.JLabel();
        lbBanThangDoiKhach = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDoiNha = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDoiKhach = new javax.swing.JTable();

        setLayout(new java.awt.GridLayout(1, 0));

        panelHome.setBackground(new java.awt.Color(0, 76, 127));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setPreferredSize(new java.awt.Dimension(1000, 600));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnDoiHinhRaSan.setBackground(new java.awt.Color(0, 76, 127));
        btnDoiHinhRaSan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDoiHinhRaSan.setForeground(new java.awt.Color(255, 255, 255));
        btnDoiHinhRaSan.setText("ĐỘI HÌNH RA SÂN");
        btnDoiHinhRaSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiHinhRaSanActionPerformed(evt);
            }
        });

        btnSuKien.setBackground(new java.awt.Color(0, 76, 127));
        btnSuKien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuKien.setForeground(new java.awt.Color(255, 255, 255));
        btnSuKien.setText("SỰ KIỆN TRONG TRẬN");
        btnSuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuKienActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(0, 76, 127));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuKien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                    .addComponent(btnDoiHinhRaSan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnDoiHinhRaSan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnSuKien)
                .addGap(37, 37, 37)
                .addComponent(btnThongKe)
                .addGap(20, 20, 20))
        );

        panelMenu13.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu13.setPreferredSize(new java.awt.Dimension(1000, 40));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Untitled-3.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnFM9.setBackground(new java.awt.Color(0, 0, 0));
        btnFM9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFM9.setForeground(new java.awt.Color(255, 255, 255));
        btnFM9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Artboard 2.png"))); // NOI18N
        btnFM9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFM9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFM9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFM9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu13Layout = new javax.swing.GroupLayout(panelMenu13);
        panelMenu13.setLayout(panelMenu13Layout);
        panelMenu13Layout.setHorizontalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFM9)
                .addContainerGap())
        );
        panelMenu13Layout.setVerticalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFM9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lbTenDoiNha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTenDoiNha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTenDoiNha.setText("Đội Nhà\n");

        lbTenDoiKhach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTenDoiKhach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTenDoiKhach.setText("Đội khách");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("-");

        lbBanThangDoiNha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbBanThangDoiNha.setText("_");

        lbBanThangDoiKhach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbBanThangDoiKhach.setText("_");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTenDoiNha, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbBanThangDoiNha)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lbBanThangDoiKhach)
                .addGap(18, 18, 18)
                .addComponent(lbTenDoiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbTenDoiNha, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbTenDoiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1)
                .addComponent(lbBanThangDoiNha)
                .addComponent(lbBanThangDoiKhach))
        );

        jScrollPane1.setPreferredSize(new java.awt.Dimension(330, 380));

        tbDoiNha.setAutoCreateRowSorter(true);
        tbDoiNha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbDoiNha);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(330, 380));

        tbDoiKhach.setAutoCreateRowSorter(true);
        tbDoiKhach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbDoiKhach);

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(panelMenu13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(panelMenu13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelHomeLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelHome);
    }// </editor-fold>//GEN-END:initComponents

    private void setLableData(){
        try{
            FinishedMatchDetailsService fs = new FinishedMatchDetailsService();
            details = fs.getMatchDetail(matchId);
            TeamService ts = new TeamService();
            String doiNha = ts.getTeamById(details.getHomeTeam()).getTeamName();
            String doiKhach = ts.getTeamById(details.getAwayTeam()).getTeamName();
            lbTenDoiNha.setText(doiNha);
            lbTenDoiKhach.setText(doiKhach);
            lbBanThangDoiNha.setText("" + details.getHomeGoals());
            lbBanThangDoiKhach.setText("" + details.getAwayGoals());
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void btnFM9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFM9ActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ScreenManager.get().clearHistory();
        if (mainFrame != null) {
            mainFrame.showHome();
        }
    }//GEN-LAST:event_btnFM9ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ScreenManager.get().back();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnDoiHinhRaSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiHinhRaSanActionPerformed
        try {
            MatchPlayerService service = new MatchPlayerService();
            List<MatchPlayers> doiNha = service.getByMatchAndTeam(matchId, details.getHomeTeam());
            List<MatchPlayers> doiKhach = service.getByMatchAndTeam(matchId, details.getAwayTeam());
            
            String[] columnNamesTableDoiHinh = {"Tên cầu thủ", "Vị trí", "Vai trò"};
            modelDoiNha = new DefaultTableModel(columnNamesTableDoiHinh, 0);
            modelDoiKhach = new DefaultTableModel(columnNamesTableDoiHinh, 0);
            tbDoiNha.setModel(modelDoiNha);
            tbDoiKhach.setModel(modelDoiKhach);
            
            tbDoiNha.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            TableColumnModel colHome = tbDoiNha.getColumnModel();
        
            colHome.getColumn(0).setPreferredWidth(150); //Tên cầu thủ
            colHome.getColumn(1).setPreferredWidth(100); // Vị trí
            colHome.getColumn(2).setPreferredWidth(80); // Vai trò

            for (int i = 0; i < colHome.getColumnCount(); i++) {
                colHome.getColumn(i).setResizable(false);
            }
            
            tbDoiKhach.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            TableColumnModel colAway = tbDoiKhach.getColumnModel();
        
            colAway.getColumn(0).setPreferredWidth(150); //Tên cầu thủ
            colAway.getColumn(1).setPreferredWidth(100); // Vị trí
            colAway.getColumn(2).setPreferredWidth(80); // Vai trò

            for (int i = 0; i < colAway.getColumnCount(); i++) {
                colAway.getColumn(i).setResizable(false);
            }
            
            PlayerService pService = new PlayerService();
            for(MatchPlayers mp : doiNha){
                Player player = pService.getPlayerById(mp.getPlayerId());
                String role = mp.getPlayerRole().equals(PlayerRole.STARTING) ? "Đá chính" : "Dự bị";
                modelDoiNha.addRow(new Object[]{player.getPlayerName(), player.getPosition(), role});
            }
            
            for(MatchPlayers mp : doiKhach){
                Player player = pService.getPlayerById(mp.getPlayerId());
                String role = mp.getPlayerRole().equals(PlayerRole.STARTING) ? "Đá chính" : "Dự bị";
                modelDoiKhach.addRow(new Object[]{player.getPlayerName(), player.getPosition(), role});
            }
            
            
            
        } catch(Exception e){
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btnDoiHinhRaSanActionPerformed

    private void btnSuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuKienActionPerformed
        try {
            MatchEventService service = new MatchEventService();
            List<MatchEvents> suKienDoiNha = service.getEventsOfTeamInMatch(matchId, details.getHomeTeam());
            List<MatchEvents> suKienDoiKhach = service.getEventsOfTeamInMatch(matchId, details.getAwayTeam());
            
            String[] columnNamesTableSuKien = {"Cầu thủ", "Loại sự kiện", "Phút"};
            modelDoiNha = new DefaultTableModel(columnNamesTableSuKien, 0);
            modelDoiKhach = new DefaultTableModel(columnNamesTableSuKien, 0);
            
            tbDoiNha.setModel(modelDoiNha);
            tbDoiKhach.setModel(modelDoiKhach);
            
            tbDoiNha.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            TableColumnModel colHome = tbDoiNha.getColumnModel();
        
            colHome.getColumn(0).setPreferredWidth(150); //Tên cầu thủ
            colHome.getColumn(1).setPreferredWidth(130); // Loại sự kiện
            colHome.getColumn(2).setPreferredWidth(50); // Phút

            for (int i = 0; i < colHome.getColumnCount(); i++) {
                colHome.getColumn(i).setResizable(false);
            }
            
            tbDoiKhach.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            TableColumnModel colAway = tbDoiKhach.getColumnModel();
        
            colAway.getColumn(0).setPreferredWidth(150); //Tên cầu thủ
            colAway.getColumn(1).setPreferredWidth(130); // Loại sự kiện
            colAway.getColumn(2).setPreferredWidth(50); // Phút

            for (int i = 0; i < colAway.getColumnCount(); i++) {
                colAway.getColumn(i).setResizable(false);
            }
            
            
            PlayerService pService = new PlayerService();
            for(MatchEvents me : suKienDoiNha){
                String playerName = pService.getPlayerById(me.getPlayerId()).getPlayerName();
                modelDoiNha.addRow(new Object[]{playerName, me.getEventType().getVietnamese(), me.getEventTime()});
            }
            
            for(MatchEvents me : suKienDoiKhach){
                String playerName = pService.getPlayerById(me.getPlayerId()).getPlayerName();
                modelDoiKhach.addRow(new Object[]{playerName, me.getEventType().getVietnamese(), me.getEventTime()});
            }
            
            
            
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSuKienActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        try {
            MatchEventService service = new MatchEventService();
            
            String[] columnNamesTableThongKe = {"Tiêu chí", "Số lượng"};
            modelDoiNha = new DefaultTableModel(columnNamesTableThongKe, 0);
            modelDoiKhach = new DefaultTableModel(columnNamesTableThongKe, 0);
            
            tbDoiNha.setModel(modelDoiNha);
            tbDoiKhach.setModel(modelDoiKhach);
            
            tbDoiNha.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            TableColumnModel colHome = tbDoiNha.getColumnModel();
        
            colHome.getColumn(0).setPreferredWidth(180); //Tiêu chí
            colHome.getColumn(1).setPreferredWidth(150); // Số lượng
            
            for (int i = 0; i < colHome.getColumnCount(); i++) {
                colHome.getColumn(i).setResizable(false);
            }
            
            tbDoiKhach.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            TableColumnModel colAway = tbDoiKhach.getColumnModel();
        
            colAway.getColumn(0).setPreferredWidth(180); //Tiêu chí
            colAway.getColumn(1).setPreferredWidth(150); // Số lượng

            for (int i = 0; i < colAway.getColumnCount(); i++) {
                colAway.getColumn(i).setResizable(false);
            }
            
            modelDoiNha.addRow(new Object[]{"Tổng số bàn thắng" , details.getHomeGoals()});
            modelDoiNha.addRow(new Object[]{"Số bàn thắng trên chấm pen" , service.countPenaltyGoalsOfTemInMatch(matchId, details.getHomeTeam())});
            modelDoiNha.addRow(new Object[]{"Số lần phản lưới nhà" , service.countOwnGoalsOfTeamInMatch(matchId, details.getHomeTeam())});
            modelDoiNha.addRow(new Object[]{"Số lần phạm lỗi" , service.countFoulsOfTeamInMatch(matchId, details.getHomeTeam())});
            modelDoiNha.addRow(new Object[]{"Số thẻ vàng" , service.countYellowCardsOfTeamInMatch(matchId, details.getHomeTeam())});
            modelDoiNha.addRow(new Object[]{"Số thẻ đỏ" , service.countRedCardsOfTeamInMatch(matchId, details.getHomeTeam())});
            
            modelDoiKhach.addRow(new Object[]{"Tổng số bàn thắng" , details.getAwayGoals()});
            modelDoiKhach.addRow(new Object[]{"Số bàn thắng trên chấm pen" , service.countPenaltyGoalsOfTemInMatch(matchId, details.getAwayTeam())});
            modelDoiKhach.addRow(new Object[]{"Số lần phản lưới nhà" , service.countOwnGoalsOfTeamInMatch(matchId, details.getAwayTeam())});
            modelDoiKhach.addRow(new Object[]{"Số lần phạm lỗi" , service.countFoulsOfTeamInMatch(matchId, details.getAwayTeam())});
            modelDoiKhach.addRow(new Object[]{"Số thẻ vàng" , service.countYellowCardsOfTeamInMatch(matchId, details.getAwayTeam())});
            modelDoiKhach.addRow(new Object[]{"Số thẻ đỏ" , service.countRedCardsOfTeamInMatch(matchId, details.getAwayTeam())});
            
            
            
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnThongKeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiHinhRaSan;
    private javax.swing.JButton btnFM9;
    private javax.swing.JButton btnSuKien;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbBanThangDoiKhach;
    private javax.swing.JLabel lbBanThangDoiNha;
    private javax.swing.JLabel lbTenDoiKhach;
    private javax.swing.JLabel lbTenDoiNha;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu13;
    private javax.swing.JTable tbDoiKhach;
    private javax.swing.JTable tbDoiNha;
    // End of variables declaration//GEN-END:variables
}
