/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package N23DCCN058.fm.ui.panel;

import N23DCCN058.fm.model.LeagueTableRow;
import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.Referee;
import N23DCCN058.fm.model.RefereeStatistic;
import N23DCCN058.fm.service.LeagueTableService;
import N23DCCN058.fm.service.StatisticService;
import N23DCCN058.fm.ui.frame.MainFrame;
import N23DCCN058.fm.ui.frame.ScreenManager;
import java.util.List;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author admin
 */
public class ThongKePanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKePanel
     */
    private DefaultTableModel bangXepHang, vuaPhaLuoi, xhTrongTai;
    
    public ThongKePanel() {
        initComponents();
        setSize(1000,600);
        tb.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        bangXepHang = new DefaultTableModel(new String[]{"ID", "Tên đội bóng", "ĐĐ", "T", "H", "T", "BT", "SBT", "HS", "Điểm", "Hạng"}, 0);
        vuaPhaLuoi = new DefaultTableModel(new String[]{"ID", "Tên cầu thủ", "Vị trí", "Số bàn thắng"}, 0);
        xhTrongTai = new DefaultTableModel(new String[]{"ID", "Tên trọng tài","Số điện thoại", "Số trận được giao", "Số trận đã hoàn thành"}, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panelMenu11 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        btnFM7 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(0, 76, 127));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setPreferredSize(new java.awt.Dimension(1000, 600));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(610, 460));

        tb.setAutoCreateRowSorter(true);
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tb);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setBackground(new java.awt.Color(0, 76, 127));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BẢNG XẾP HẠNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 76, 127));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("DANH SÁCH VUA PHÁ LƯỚI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 76, 127));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("XẾP HẠNG TRỌNG TÀI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(10, 10, 10))
        );

        panelMenu11.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu11.setPreferredSize(new java.awt.Dimension(1000, 40));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Untitled-3.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnFM7.setBackground(new java.awt.Color(0, 0, 0));
        btnFM7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFM7.setForeground(new java.awt.Color(255, 255, 255));
        btnFM7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Artboard 2.png"))); // NOI18N
        btnFM7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFM7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFM7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFM7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu11Layout = new javax.swing.GroupLayout(panelMenu11);
        panelMenu11.setLayout(panelMenu11Layout);
        panelMenu11Layout.setHorizontalGroup(
            panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFM7)
                .addContainerGap())
        );
        panelMenu11Layout.setVerticalGroup(
            panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFM7, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(panelMenu11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(panelMenu11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(61, 61, 61))
        );

        add(panelHome, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnFM7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFM7ActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ScreenManager.get().clearHistory();
        if (mainFrame != null) {
            mainFrame.showHome();
        }
    }//GEN-LAST:event_btnFM7ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ScreenManager.get().back();
        bangXepHang.setRowCount(0);
        vuaPhaLuoi.setRowCount(0);
        xhTrongTai.setRowCount(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        try {
            LeagueTableService service = new LeagueTableService();
            List<LeagueTableRow> ranking = service.calculateLeagueTable();
            
            bangXepHang.setRowCount(0);
            for(LeagueTableRow row : ranking)
                bangXepHang.addRow(new Object[]{row.getTeamId(), row.getTeamName(), row.getPlayed(), row.getWins(), row.getDraws(), row.getLosses(), row.getGoalsFor(), row.getGoalsAgainst(), row.getGoalDifference(), row.getPoints(), row.getRank()});
            
            tb.setModel(bangXepHang);
            
            TableColumnModel colHome = tb.getColumnModel();
        
            colHome.getColumn(0).setPreferredWidth(30); 
            colHome.getColumn(1).setPreferredWidth(150);
            colHome.getColumn(2).setPreferredWidth(45);
            colHome.getColumn(3).setPreferredWidth(45); 
            colHome.getColumn(4).setPreferredWidth(45);
            colHome.getColumn(5).setPreferredWidth(45);
            colHome.getColumn(6).setPreferredWidth(45); 
            colHome.getColumn(7).setPreferredWidth(45);
            colHome.getColumn(8).setPreferredWidth(45);
            colHome.getColumn(9).setPreferredWidth(45); 
            colHome.getColumn(10).setPreferredWidth(60);

            for (int i = 0; i < colHome.getColumnCount(); i++) {
                colHome.getColumn(i).setResizable(false);
            }
            
            
            
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            StatisticService service = new StatisticService();
            Map<Player, Integer> ranking = service.calculatePlayerRanking();
            
            vuaPhaLuoi.setRowCount(0);
            for(Map.Entry<Player, Integer> entry : ranking.entrySet())
                vuaPhaLuoi.addRow(new Object[]{entry.getKey().getPlayerId(), entry.getKey().getPlayerName(), entry.getKey().getPosition().name(), entry.getValue()});
            
            tb.setModel(vuaPhaLuoi);
            
            TableColumnModel colHome = tb.getColumnModel();
        
            colHome.getColumn(0).setPreferredWidth(50); 
            colHome.getColumn(1).setPreferredWidth(200);
            colHome.getColumn(2).setPreferredWidth(200);
            colHome.getColumn(3).setPreferredWidth(160); 

            for (int i = 0; i < colHome.getColumnCount(); i++) {
                colHome.getColumn(i).setResizable(false);
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            StatisticService service = new StatisticService();
            Map<Referee, RefereeStatistic> ranking = service.calculateRefereeRanking();
            
            xhTrongTai.setRowCount(0);
            for(Map.Entry<Referee, RefereeStatistic> entry : ranking.entrySet())
                xhTrongTai.addRow(new Object[]{entry.getKey().getRefereeId(), entry.getKey().getRefereeName(), entry.getKey().getPhoneNumber(), entry.getValue().getNumOfMatchesJoin(), entry.getValue().getNumOfFinishedMatches()});
            
            tb.setModel(xhTrongTai);
            
            TableColumnModel colHome = tb.getColumnModel();
        
            colHome.getColumn(0).setPreferredWidth(20); 
            colHome.getColumn(1).setPreferredWidth(200);
            colHome.getColumn(2).setPreferredWidth(90);
            colHome.getColumn(3).setPreferredWidth(140);
            colHome.getColumn(4).setPreferredWidth(150);

            for (int i = 0; i < colHome.getColumnCount(); i++) {
                colHome.getColumn(i).setResizable(false);
            }
            
        } catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFM7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu11;
    private javax.swing.JTable tb;
    // End of variables declaration//GEN-END:variables
}
