/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package N23DCCN058.fm.ui.panel;

import N23DCCN058.fm.exception.ServiceException;
import N23DCCN058.fm.exception.ValidationException;
import N23DCCN058.fm.model.Match;
import N23DCCN058.fm.model.MatchStatus;
import N23DCCN058.fm.model.Referee;
import N23DCCN058.fm.service.MatchService;
import N23DCCN058.fm.service.RefereeService;
import N23DCCN058.fm.ui.dialog.CapNhapThongTinTranDauDialog;
import N23DCCN058.fm.ui.dialog.ThemTranDauDialog;
import N23DCCN058.fm.ui.dialog.TimTranTheoNgayDialog;
import N23DCCN058.fm.ui.dialog.TimTranTheoTenTrongTaiDialog;
import N23DCCN058.fm.ui.frame.MainFrame;
import N23DCCN058.fm.ui.frame.ScreenManager;
import java.sql.Date;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author admin
 */
public class TranDauPanel extends javax.swing.JPanel {

    /**
     * Creates new form TranDauPanel
     */
    private DefaultTableModel model;
    private Map<Integer, Referee> lstRefereName;
    
    public TranDauPanel() {
        initComponents();
        setSize(1000,600);
        String[] columnNames = {"Id", "Trọng tài", "Ngày diễn ra", "Trạng thái"};
        model = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(model);
        
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel col = jTable1.getColumnModel();
        
        col.getColumn(0).setPreferredWidth(50); // Id 
        col.getColumn(1).setPreferredWidth(250); // Trọng tài
        col.getColumn(2).setPreferredWidth(150); // Ngày diễn ra
        col.getColumn(3).setPreferredWidth(170);  // Trạng thái
        
        for (int i = 0; i < col.getColumnCount(); i++) {
            col.getColumn(i).setResizable(false);
        }
        
        initTableSelectionListener();
        updateButtonVisibility();
        initRefereeName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnDanhSach = new javax.swing.JButton();
        btnThemTranDau = new javax.swing.JButton();
        btnSuaTranDau = new javax.swing.JButton();
        btnXoaTranDau = new javax.swing.JButton();
        btnTranDauDaDienRa = new javax.swing.JButton();
        btnTranDauChuaDienRa = new javax.swing.JButton();
        btnTimTranTheoNgay = new javax.swing.JButton();
        btnTimTranTheoTrongTai = new javax.swing.JButton();
        btnXemChiTiet = new javax.swing.JButton();
        btnGhiSuKien = new javax.swing.JButton();
        btnKetQua = new javax.swing.JButton();
        panelMenu13 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        btnFM9 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(0, 76, 127));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setPreferredSize(new java.awt.Dimension(1000, 600));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(630, 460));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnDanhSach.setBackground(new java.awt.Color(0, 76, 127));
        btnDanhSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDanhSach.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSach.setText("DANH SÁCH TRẬN ĐẤU");
        btnDanhSach.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachActionPerformed(evt);
            }
        });

        btnThemTranDau.setBackground(new java.awt.Color(0, 76, 127));
        btnThemTranDau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemTranDau.setForeground(new java.awt.Color(255, 255, 255));
        btnThemTranDau.setText("THÊM TRẬN ĐẤU");
        btnThemTranDau.setToolTipText("");
        btnThemTranDau.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnThemTranDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTranDauActionPerformed(evt);
            }
        });

        btnSuaTranDau.setBackground(new java.awt.Color(0, 76, 127));
        btnSuaTranDau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaTranDau.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaTranDau.setText("SỬA TRẬN ĐẤU");
        btnSuaTranDau.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnSuaTranDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaTranDauActionPerformed(evt);
            }
        });

        btnXoaTranDau.setBackground(new java.awt.Color(0, 76, 127));
        btnXoaTranDau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaTranDau.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTranDau.setText("XÓA TRẬN ĐẤU");
        btnXoaTranDau.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnXoaTranDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTranDauActionPerformed(evt);
            }
        });

        btnTranDauDaDienRa.setBackground(new java.awt.Color(0, 76, 127));
        btnTranDauDaDienRa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTranDauDaDienRa.setForeground(new java.awt.Color(255, 255, 255));
        btnTranDauDaDienRa.setText("TRẬN ĐẤU ĐÃ DIỄN RA");
        btnTranDauDaDienRa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnTranDauDaDienRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranDauDaDienRaActionPerformed(evt);
            }
        });

        btnTranDauChuaDienRa.setBackground(new java.awt.Color(0, 76, 127));
        btnTranDauChuaDienRa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTranDauChuaDienRa.setForeground(new java.awt.Color(255, 255, 255));
        btnTranDauChuaDienRa.setText("TRẬN ĐẤU CHƯA DIỄN RA");
        btnTranDauChuaDienRa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnTranDauChuaDienRa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranDauChuaDienRaActionPerformed(evt);
            }
        });

        btnTimTranTheoNgay.setBackground(new java.awt.Color(0, 76, 127));
        btnTimTranTheoNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimTranTheoNgay.setForeground(new java.awt.Color(255, 255, 255));
        btnTimTranTheoNgay.setText("TÌM TRẬN THEO NGÀY");
        btnTimTranTheoNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTranTheoNgayActionPerformed(evt);
            }
        });

        btnTimTranTheoTrongTai.setBackground(new java.awt.Color(0, 76, 127));
        btnTimTranTheoTrongTai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimTranTheoTrongTai.setForeground(new java.awt.Color(255, 255, 255));
        btnTimTranTheoTrongTai.setText("TÌM TRẬN THEO TRỌNG TÀI");
        btnTimTranTheoTrongTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTranTheoTrongTaiActionPerformed(evt);
            }
        });

        btnXemChiTiet.setBackground(new java.awt.Color(0, 76, 127));
        btnXemChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXemChiTiet.setForeground(new java.awt.Color(255, 255, 255));
        btnXemChiTiet.setText("XEM CHI TIẾT");
        btnXemChiTiet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        btnGhiSuKien.setBackground(new java.awt.Color(0, 76, 127));
        btnGhiSuKien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGhiSuKien.setForeground(new java.awt.Color(255, 255, 255));
        btnGhiSuKien.setText("GHI SỰ KIỆN");
        btnGhiSuKien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnGhiSuKien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiSuKienActionPerformed(evt);
            }
        });

        btnKetQua.setBackground(new java.awt.Color(0, 76, 127));
        btnKetQua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKetQua.setForeground(new java.awt.Color(255, 255, 255));
        btnKetQua.setText("XEM KẾT QUẢ");
        btnKetQua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnKetQua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetQuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTimTranTheoTrongTai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTimTranTheoNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTranDauChuaDienRa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTranDauDaDienRa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaTranDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaTranDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemTranDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXemChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGhiSuKien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKetQua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnDanhSach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnThemTranDau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaTranDau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaTranDau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXemChiTiet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGhiSuKien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKetQua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTranDauDaDienRa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTranDauChuaDienRa)
                .addGap(9, 9, 9)
                .addComponent(btnTimTranTheoNgay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTimTranTheoTrongTai)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelMenu13.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu13.setPreferredSize(new java.awt.Dimension(1000, 40));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Untitled-3.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnFM9.setBackground(new java.awt.Color(0, 0, 0));
        btnFM9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFM9.setForeground(new java.awt.Color(255, 255, 255));
        btnFM9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Artboard 2.png"))); // NOI18N
        btnFM9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFM9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFM9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFM9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu13Layout = new javax.swing.GroupLayout(panelMenu13);
        panelMenu13.setLayout(panelMenu13Layout);
        panelMenu13Layout.setHorizontalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFM9)
                .addContainerGap())
        );
        panelMenu13Layout.setVerticalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFM9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(panelMenu13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(panelMenu13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        add(panelHome, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void initTableSelectionListener(){
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { // Đảm bảo chỉ xử lý khi chọn xong
                updateButtonVisibility();
            }   
        }); 
    }
    
    private void updateButtonVisibility() {
        int selectedCount = jTable1.getSelectedRowCount();

                // Nếu chưa chọn hoặc chọn > 1 dòng -> disable nút
        boolean enable = (selectedCount == 1);
        btnSuaTranDau.setEnabled(enable);
        btnXoaTranDau.setEnabled(enable);
        btnXemChiTiet.setEnabled(enable);
        btnGhiSuKien.setEnabled(enable);
        btnKetQua.setEnabled(enable && jTable1.getValueAt(jTable1.getSelectedRow(), 3).toString().equalsIgnoreCase("Đã diễn ra"));
    }
    
    void resetTableData(){
        model.setRowCount(0);
    }
    
    private void hienDanhSach(){
        MatchService mService = new MatchService();
        try {
            List<Match> list = mService.getAllMatch();
            hienDanhSach(list);
        } catch (ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Không thể lấy dữ liệu!", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    private void initRefereeName(){
        try {
            RefereeService rService = new RefereeService();
            lstRefereName = rService.getAllReferee()
                    .stream()
                    .collect(Collectors.toMap(
                            referee -> referee.getRefereeId()
                            , referee -> referee
                    ));

        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Không thể lấy dữ liệu!", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void hienDanhSach(List<Match> list){
        resetTableData();
        initRefereeName();
        for(Match match : list){
            Integer matchId = match.getMatchId();
            Referee referee = lstRefereName.get(match.getRefereeId());
            Date matchDate = match.getMatchDate();
            String status = match.getMatchStatus().equals(MatchStatus.DA_DIEN_RA) ? "Đã diễn ra" : "Chưa diễn ra";

            model.addRow(new Object[]{matchId, referee, matchDate, status});
        }

        model.fireTableDataChanged();
        jTable1.revalidate();
        jTable1.repaint();
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
       
    }
    
    private void btnDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachActionPerformed
        hienDanhSach();
    }//GEN-LAST:event_btnDanhSachActionPerformed

    private void btnTimTranTheoNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTranTheoNgayActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        TimTranTheoNgayDialog dialog = new TimTranTheoNgayDialog(mainFrame, true);
        //dialog.setVisible(true);
        if (mainFrame != null) {
        // Tạo GlassPane làm mờ
            final javax.swing.JPanel glassPane = new javax.swing.JPanel() {
            @Override
                protected void paintComponent(java.awt.Graphics g) {
                    super.paintComponent(g);
                // Vẽ lớp phủ màu đen trong suốt
                    g.setColor(new java.awt.Color(0, 0, 0, 128)); // 128 = 50% opacity
                    g.fillRect(0, 0, getWidth(), getHeight());
                }
            };
        
        glassPane.setOpaque(false);
        // Chặn tương tác với các component bên dưới
        glassPane.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                dialog.dispose();// Click vào vùng mờ sẽ đóng dialog
            }
        });
        
        // Đặt glassPane
        mainFrame.setGlassPane(glassPane);
        glassPane.setVisible(true);
        
        // Hiển thị dialog
        
        
        // Thêm listener để tắt glassPane khi đóng dialog
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                glassPane.setVisible(false);
            }
        });
        
        
        dialog.setVisible(true);
    }
        
        if(!dialog.isConfirm()) return;
        
        try {
            MatchService mService = new MatchService();
            Date date = dialog.getDate();
            List<Match> lst = mService.searchMatchByDate(date);
            hienDanhSach(lst);
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimTranTheoNgayActionPerformed

    private void btnTimTranTheoTrongTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTranTheoTrongTaiActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        TimTranTheoTenTrongTaiDialog dialog = new TimTranTheoTenTrongTaiDialog(mainFrame, true);
        dialog.setVisible(true);
        
        if(!dialog.isConfirm()) return;
        
        try {
            MatchService mService = new MatchService();
            Referee referee = dialog.getTrongTai();
            List<Match> lst = mService.searchMatchByRefereeId(referee.getRefereeId());
            hienDanhSach(lst);
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimTranTheoTrongTaiActionPerformed

    private void btnThemTranDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTranDauActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ThemTranDauDialog dialog = new ThemTranDauDialog(mainFrame, true);
        dialog.setVisible(true);
        
        if(!dialog.isConfirm()) return;
        
        try {
            MatchService mService = new MatchService();
            Match match = dialog.getMatch();
            mService.addMatch(match);
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        hienDanhSach();
    }//GEN-LAST:event_btnThemTranDauActionPerformed

    private void btnXoaTranDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTranDauActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa trận đấu này không?\n Xóa trận đấu sẽ xóa toàn bộ thông tin liên quan!",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );   
        if(choice != JOptionPane.YES_OPTION) return;
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 trận đấu bóng để xóa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        try {
            MatchService ms = new MatchService();
            ms.deleteMatchById(id);
            hienDanhSach();
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaTranDauActionPerformed

    private void btnFM9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFM9ActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ScreenManager.get().clearHistory();
        if (mainFrame != null) {
            mainFrame.showHome();
        }
    }//GEN-LAST:event_btnFM9ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        ScreenManager.get().back();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 trận đấu để xem chi tiết!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        mainFrame.showChiTietTranDau(id);
    }//GEN-LAST:event_btnXemChiTietActionPerformed

    private void btnGhiSuKienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiSuKienActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 trận đấu để ghi sự kiện!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0); 
        try {
            MatchService service = new MatchService();
            if(!service.isReady(id)){
                JOptionPane.showMessageDialog(this, "Không thể ghi sự kiện cho trận đấu này!\n Chưa đủ thông tin về đội bóng và cầu thủ tham gia. \n Chọn XEM CHI TIẾT để thêm thông tin cho trận đấu. ");
                return;
            }
        } catch(Exception e){
            e.printStackTrace();
        }
        mainFrame.showGhiSuKien(id);
    }//GEN-LAST:event_btnGhiSuKienActionPerformed

    private void btnTranDauDaDienRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranDauDaDienRaActionPerformed
        try {
            MatchService mService = new MatchService();
            List<Match> lst = mService.getAllFinishedMatch();
            hienDanhSach(lst);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTranDauDaDienRaActionPerformed

    private void btnTranDauChuaDienRaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranDauChuaDienRaActionPerformed
        try {
            MatchService mService = new MatchService();
            List<Match> lst = mService.getAllUnfinishedMatch();
            hienDanhSach(lst);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTranDauChuaDienRaActionPerformed

    private void btnSuaTranDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaTranDauActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ bóng để sửa!");
            return;
        }

        int matchId = (int) jTable1.getValueAt(selectedRow, 0);
        Referee referee = (Referee) jTable1.getValueAt(selectedRow, 1);
        Date date = (Date) jTable1.getValueAt(selectedRow, 2);
        MatchStatus matchStatus = jTable1.getValueAt(selectedRow, 3).toString().equalsIgnoreCase("Đã diễn ra") ? MatchStatus.DA_DIEN_RA : MatchStatus.CHUA_DIEN_RA;
        
        Match match = new Match(matchId, referee.getRefereeId(), date, matchStatus);
        
        CapNhapThongTinTranDauDialog dialog = new CapNhapThongTinTranDauDialog(mainFrame, true, match);
        dialog.setVisible(true);
        
        
        if(!dialog.isConfirm()) return;
        
        try {
            MatchService mService = new MatchService();
            Match updatedMatch = dialog.getMatch();
            mService.updateMatch(updatedMatch);
            hienDanhSach();
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSuaTranDauActionPerformed

    private void btnKetQuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetQuaActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 trận đấu bóng để xem kết quả!");
            return;
        }
        
        if(jTable1.getValueAt(selectedRow, 3).toString().equalsIgnoreCase("Chưa diễn ra")){
            JOptionPane.showMessageDialog(this, "Không thể xem kết quả của trận đấu chưa diễn ra!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        mainFrame.showKetQuaTranDau(id);
    }//GEN-LAST:event_btnKetQuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSach;
    private javax.swing.JButton btnFM9;
    private javax.swing.JButton btnGhiSuKien;
    private javax.swing.JButton btnKetQua;
    private javax.swing.JButton btnSuaTranDau;
    private javax.swing.JButton btnThemTranDau;
    private javax.swing.JButton btnTimTranTheoNgay;
    private javax.swing.JButton btnTimTranTheoTrongTai;
    private javax.swing.JButton btnTranDauChuaDienRa;
    private javax.swing.JButton btnTranDauDaDienRa;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JButton btnXoaTranDau;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu13;
    // End of variables declaration//GEN-END:variables
}
