/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package N23DCCN058.fm.ui.panel;

import N23DCCN058.fm.exception.ServiceException;
import N23DCCN058.fm.exception.ValidationException;
import N23DCCN058.fm.model.Referee;
import N23DCCN058.fm.model.RefereeStatistic;
import N23DCCN058.fm.service.RefereeService;
import N23DCCN058.fm.service.StatisticService;
import N23DCCN058.fm.ui.dialog.CapNhapTrongTaiDialog;
import N23DCCN058.fm.ui.dialog.ThemTrongTaiDialog;
import N23DCCN058.fm.ui.dialog.TimTrongTaiDialog;
import N23DCCN058.fm.ui.frame.MainFrame;
import N23DCCN058.fm.ui.frame.ScreenManager;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author admin
 */
public class TrongTaiPanel extends javax.swing.JPanel {

    /**
     * Creates new form TrongTaiPanel
     */
    
    DefaultTableModel model;
    
    public TrongTaiPanel() {
        initComponents();
        setSize(1000,600);
        String[] columnNames = {"Id", "Tên trọng tài", "Số điện thoại"};
        model = new DefaultTableModel(columnNames, 0);
        jTable1.setModel(model);
        
        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel col = jTable1.getColumnModel();
        
        col.getColumn(0).setPreferredWidth(50); // Id 
        col.getColumn(1).setPreferredWidth(330); // Tên trọng tài
        col.getColumn(2).setPreferredWidth(335); // Số điện thoại
        
        for (int i = 0; i < col.getColumnCount(); i++) {
            col.getColumn(i).setResizable(false);
        }
        
        initTableSelectionListener();
        updateButtonVisibility();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnDanhSach = new javax.swing.JButton();
        btnThemTrongTai = new javax.swing.JButton();
        btnXemThongSo = new javax.swing.JButton();
        btnSuaThongTin = new javax.swing.JButton();
        btnXoaTrongTai = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        panelMenu13 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        btnFM9 = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(0, 76, 127));
        panelHome.setForeground(new java.awt.Color(255, 255, 255));
        panelHome.setPreferredSize(new java.awt.Dimension(1000, 600));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnDanhSach.setBackground(new java.awt.Color(0, 76, 127));
        btnDanhSach.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDanhSach.setForeground(new java.awt.Color(255, 255, 255));
        btnDanhSach.setText("DANH SÁCH TRỌNG TÀI");
        btnDanhSach.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnDanhSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanhSachActionPerformed(evt);
            }
        });

        btnThemTrongTai.setBackground(new java.awt.Color(0, 76, 127));
        btnThemTrongTai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemTrongTai.setForeground(new java.awt.Color(255, 255, 255));
        btnThemTrongTai.setText("THÊM TRỌNG TÀI");
        btnThemTrongTai.setToolTipText("");
        btnThemTrongTai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnThemTrongTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTrongTaiActionPerformed(evt);
            }
        });

        btnXemThongSo.setBackground(new java.awt.Color(0, 76, 127));
        btnXemThongSo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXemThongSo.setForeground(new java.awt.Color(255, 255, 255));
        btnXemThongSo.setText("XEM THÔNG SỐ\n");
        btnXemThongSo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnXemThongSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemThongSoActionPerformed(evt);
            }
        });

        btnSuaThongTin.setBackground(new java.awt.Color(0, 76, 127));
        btnSuaThongTin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaThongTin.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaThongTin.setText("SỬA THÔNG TIN");
        btnSuaThongTin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThongTinActionPerformed(evt);
            }
        });

        btnXoaTrongTai.setBackground(new java.awt.Color(0, 76, 127));
        btnXoaTrongTai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaTrongTai.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTrongTai.setText("XÓA TRỌNG TÀI");
        btnXoaTrongTai.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(153, 153, 153), new java.awt.Color(51, 51, 51)));
        btnXoaTrongTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrongTaiActionPerformed(evt);
            }
        });

        btnTim.setBackground(new java.awt.Color(0, 76, 127));
        btnTim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setText("TÌM TRỌNG TÀI");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTim, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnDanhSach, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                        .addComponent(btnThemTrongTai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXemThongSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSuaThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaTrongTai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnDanhSach)
                .addGap(18, 18, 18)
                .addComponent(btnThemTrongTai)
                .addGap(18, 18, 18)
                .addComponent(btnTim)
                .addGap(18, 18, 18)
                .addComponent(btnXemThongSo)
                .addGap(18, 18, 18)
                .addComponent(btnSuaThongTin)
                .addGap(18, 18, 18)
                .addComponent(btnXoaTrongTai)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        panelMenu13.setBackground(new java.awt.Color(51, 51, 51));
        panelMenu13.setPreferredSize(new java.awt.Dimension(1000, 40));

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Untitled-3.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        btnFM9.setBackground(new java.awt.Color(0, 0, 0));
        btnFM9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFM9.setForeground(new java.awt.Color(255, 255, 255));
        btnFM9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/Artboard 2.png"))); // NOI18N
        btnFM9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFM9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnFM9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFM9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenu13Layout = new javax.swing.GroupLayout(panelMenu13);
        panelMenu13.setLayout(panelMenu13Layout);
        panelMenu13Layout.setHorizontalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFM9)
                .addContainerGap())
        );
        panelMenu13Layout.setVerticalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFM9, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addComponent(panelMenu13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(panelMenu13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelHomeLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );

        add(panelHome, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void initTableSelectionListener(){
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { // Đảm bảo chỉ xử lý khi chọn xong
                updateButtonVisibility();
            }   
        }); 
    }
    
    private void updateButtonVisibility() {
        int selectedCount = jTable1.getSelectedRowCount();
        // Nếu chưa chọn hoặc chọn > 1 dòng -> disable nút
        boolean enable = (selectedCount == 1);
        btnXemThongSo.setEnabled(enable);
        btnSuaThongTin.setEnabled(enable);
        btnXoaTrongTai.setEnabled(enable);
    }
    
    void resetTableData(){
        model.setRowCount(0);
    }
    
    private void hienDanhSach(){
        RefereeService rService = new RefereeService();
        try {
            List<Referee>list = rService.getAllReferee();
            hienDanhSach(list);
        } catch (ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Không thể lấy dữ liệu!", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    
    private void hienDanhSach(List<Referee> list){
        resetTableData();
        for(Referee referee : list) model.addRow(referee.toObjectArray());

        model.fireTableDataChanged();
        jTable1.revalidate();
        jTable1.repaint();
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
    }
    
    private void btnDanhSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanhSachActionPerformed
        hienDanhSach();
    }//GEN-LAST:event_btnDanhSachActionPerformed

    private void btnThemTrongTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTrongTaiActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ThemTrongTaiDialog dialog = new ThemTrongTaiDialog(mainFrame, true);
        //dialog.setVisible(true);
        if (mainFrame != null) {
        // Tạo GlassPane làm mờ
            final javax.swing.JPanel glassPane = new javax.swing.JPanel() {
            @Override
                protected void paintComponent(java.awt.Graphics g) {
                    super.paintComponent(g);
                // Vẽ lớp phủ màu đen trong suốt
                    g.setColor(new java.awt.Color(0, 0, 0, 128)); // 128 = 50% opacity
                    g.fillRect(0, 0, getWidth(), getHeight());
                }
            };
        
        glassPane.setOpaque(false);
        // Chặn tương tác với các component bên dưới
        glassPane.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                dialog.dispose();// Click vào vùng mờ sẽ đóng dialog
            }
        });
        
        // Đặt glassPane
        mainFrame.setGlassPane(glassPane);
        glassPane.setVisible(true);
        
        // Hiển thị dialog
        
        
        // Thêm listener để tắt glassPane khi đóng dialog
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                glassPane.setVisible(false);
            }
        });
        
        
        dialog.setVisible(true);
    }
        if(!dialog.isConfirm()) return;
        
        try {
            RefereeService service = new RefereeService();
            Referee referee = dialog.getRefereeFromTextFields();
            service.addReferee(referee);
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
        hienDanhSach();
    }//GEN-LAST:event_btnThemTrongTaiActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        TimTrongTaiDialog dialog = new TimTrongTaiDialog(mainFrame, true);
        //dialog.setVisible(true);
        if (mainFrame != null) {
        // Tạo GlassPane làm mờ
            final javax.swing.JPanel glassPane = new javax.swing.JPanel() {
            @Override
                protected void paintComponent(java.awt.Graphics g) {
                    super.paintComponent(g);
                // Vẽ lớp phủ màu đen trong suốt
                    g.setColor(new java.awt.Color(0, 0, 0, 128)); // 128 = 50% opacity
                    g.fillRect(0, 0, getWidth(), getHeight());
                }
            };
        
        glassPane.setOpaque(false);
        // Chặn tương tác với các component bên dưới
        glassPane.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                dialog.dispose();// Click vào vùng mờ sẽ đóng dialog
            }
        });
        
        // Đặt glassPane
        mainFrame.setGlassPane(glassPane);
        glassPane.setVisible(true);
        
        // Hiển thị dialog
        
        
        // Thêm listener để tắt glassPane khi đóng dialog
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                glassPane.setVisible(false);
            }
        });
        
        
        dialog.setVisible(true);
    }
        if(!dialog.isConfirm()) return;
        
        try {
            RefereeService service = new RefereeService();
            Referee referee = dialog.getRefereeFromTextFields();
            List<Referee> lst = service.searchReferee(referee);
            hienDanhSach(lst);
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnXoaTrongTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrongTaiActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa cầu thủ này không?\n Xóa cầu thủ sẽ xóa toàn bộ thông tin liên quan!",
                "Xác nhận xóa",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
        );   
        if(choice != JOptionPane.YES_OPTION) return;
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ bóng để xóa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        try {
            RefereeService rs = new RefereeService();
            rs.deleteRefereeById(id);
            hienDanhSach();
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXoaTrongTaiActionPerformed

    private void btnFM9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFM9ActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ScreenManager.get().clearHistory();
        if (mainFrame != null) {
            mainFrame.showHome();
        }
    }//GEN-LAST:event_btnFM9ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        resetTableData();
        ScreenManager.get().back();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnXemThongSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemThongSoActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ để sửa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        
        try {
            StatisticService sService = new StatisticService();
            RefereeStatistic rs = sService.getRefereeStatistic(id);
            RefereeService rService = new RefereeService();
            Referee referee = rService.getRefereeById(id);
            String info = "Tên trọng tài: " + referee.getRefereeName() + "\n" 
                        + "Số điện thoại: " + referee.getPhoneNumber() + "\n"
                        + "Số trận được phân công: " + rs.getNumOfMatchesJoin() + "\n"
                        + "Số trận đã hoàn thành: " + rs.getNumOfFinishedMatches();
            JOptionPane.showMessageDialog(this, info, "Thông số trọng tài" , JOptionPane.INFORMATION_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnXemThongSoActionPerformed

    private void btnSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThongTinActionPerformed
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ bóng để sửa!");
            return;
        }
        
        int id = (int) jTable1.getValueAt(selectedRow, 0);
        String name = jTable1.getValueAt(selectedRow, 1).toString();
        String phoneNumber = jTable1.getValueAt(selectedRow, 2).toString();
        
        Referee referee = new Referee(id, name, phoneNumber);
        
        CapNhapTrongTaiDialog dialog = new CapNhapTrongTaiDialog(mainFrame, true, referee);
        dialog.setVisible(true);
        
        if(!dialog.isConfirm()) return;
        
        try {
            RefereeService rs = new RefereeService();
            Referee updatedReferee = dialog.getRefereeFromTextFields();
            rs.updateReferee(updatedReferee);
            hienDanhSach();
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.WARNING_MESSAGE);
        } catch(ServiceException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Lỗi hệ thống!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaThongTinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanhSach;
    private javax.swing.JButton btnFM9;
    private javax.swing.JButton btnSuaThongTin;
    private javax.swing.JButton btnThemTrongTai;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXemThongSo;
    private javax.swing.JButton btnXoaTrongTai;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panelMenu13;
    // End of variables declaration//GEN-END:variables
}
