/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package N23DCCN058.fm.ui.dialog;

import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.PlayerPosition;
import N23DCCN058.fm.model.Team;
import N23DCCN058.fm.service.PlayerService;
import N23DCCN058.fm.service.TeamService;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author WokWee
 */
public class ChonDoiHinhDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChonDoiHinhDialog.class.getName());

    /**
     * Creates new form ChonDoiHinhDialog
     */
    private int teamId, totalStarting,totalNor, totalSub, totalGk;
    private DefaultTableModel modelDanhSach, modelDaChinh, modelDuBi;
    private List<Player> list;
    private Map<Integer, Player> map;
    private List<Player> daChinh, duBi;
    private boolean isConfirm, isSelectedPlayer;
    
    public ChonDoiHinhDialog(java.awt.Frame parent, boolean modal) {
        this(parent, modal, -1, false);
    }
    
    public ChonDoiHinhDialog(java.awt.Frame parent, boolean modal, int teamId, boolean isSelectedPlayer) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(parent);
        
        this.teamId = teamId;
        daChinh = new ArrayList<>();
        duBi = new ArrayList<>();
        isConfirm = false;
        this.isSelectedPlayer = isSelectedPlayer;
        
        String[] columnNames = {"Id", "Tên cầu thủ", "Vị trí"};
        modelDanhSach = new DefaultTableModel(columnNames, 0);
        modelDaChinh = new DefaultTableModel(columnNames, 0);
        modelDuBi = new DefaultTableModel(columnNames, 0);
        tbDaChinh.setModel(modelDaChinh);
        tbDuBi.setModel(modelDuBi);
        tbDanhSach.setModel(modelDanhSach);
        
        tbDanhSach.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel colDS = tbDanhSach.getColumnModel();
        
        colDS.getColumn(0).setPreferredWidth(35); // Id cầu thủ
        colDS.getColumn(1).setPreferredWidth(130); // Tên cầu thủ
        colDS.getColumn(2).setPreferredWidth(98); // Ngày sinh
        
        for (int i = 0; i < colDS.getColumnCount(); i++) {
            colDS.getColumn(i).setResizable(false);
        }
        
        tbDaChinh.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel colDaChinh = tbDaChinh.getColumnModel();
        
        colDaChinh.getColumn(0).setPreferredWidth(35); // Id cầu thủ
        colDaChinh.getColumn(1).setPreferredWidth(130); // Tên cầu thủ
        colDaChinh.getColumn(2).setPreferredWidth(98); // Ngày sinh
        
        for (int i = 0; i < colDaChinh.getColumnCount(); i++) {
            colDaChinh.getColumn(i).setResizable(false);
        }
        
        tbDuBi.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel colDuBi = tbDuBi.getColumnModel();
        
        colDuBi.getColumn(0).setPreferredWidth(35); // Id cầu thủ
        colDuBi.getColumn(1).setPreferredWidth(130); // Tên cầu thủ
        colDuBi.getColumn(2).setPreferredWidth(98); // Ngày sinh
        
        for (int i = 0; i < colDuBi.getColumnCount(); i++) {
            colDuBi.getColumn(i).setResizable(false);
        }
        
        getPlayerList();
        initTableDanhSachData();
        initLabelTeamName();
        initTableSelectionListener();
        
        btnThemDaChinh.setEnabled(false);
        btnThemDuBi.setEnabled(false);
        btnXoa.setEnabled(false);
        
        updateLabelCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbTenDoi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDaChinh = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDuBi = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbDanhSach = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnThemDaChinh = new javax.swing.JButton();
        btnThemDuBi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lbTotalStartingPlayer = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbTotalStartingGk = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbTotalSub = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnHuy = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Danh sách dự bị:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 76, 127));
        jLabel2.setText("CHỌN CẦU THỦ");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Đội: ");

        lbTenDoi.setBackground(new java.awt.Color(255, 255, 255));
        lbTenDoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbTenDoi.setText("TÊN ĐỘI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTenDoi, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTenDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbDaChinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbDaChinh);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Đá chính:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Dự bị:");

        tbDuBi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbDuBi);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Danh sách cầu thủ:");

        jScrollPane3.setPreferredSize(new java.awt.Dimension(450, 400));

        tbDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tbDanhSach);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnThemDaChinh.setBackground(new java.awt.Color(0, 76, 127));
        btnThemDaChinh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemDaChinh.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDaChinh.setText("Thêm Vào Danh Sách Đá Chính");
        btnThemDaChinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDaChinhActionPerformed(evt);
            }
        });

        btnThemDuBi.setBackground(new java.awt.Color(0, 76, 127));
        btnThemDuBi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThemDuBi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDuBi.setText("Thêm Vào Danh Sách Dự Bị");
        btnThemDuBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDuBiActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(0, 76, 127));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa Khỏi Danh Sách");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemDaChinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemDuBi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnThemDaChinh)
                .addGap(18, 18, 18)
                .addComponent(btnThemDuBi)
                .addGap(18, 18, 18)
                .addComponent(btnXoa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbTotalStartingPlayer.setText("0");

        jLabel9.setText("/5");

        jLabel10.setText("GK:");

        lbTotalStartingGk.setText("0");

        jLabel12.setText("/1");

        lbTotalSub.setText("0");

        jLabel14.setText("/6");

        btnHuy.setBackground(new java.awt.Color(0, 76, 127));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        btnLuu.setBackground(new java.awt.Color(0, 76, 127));
        btnLuu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuu.setForeground(new java.awt.Color(255, 255, 255));
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalSub)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalStartingPlayer)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalStartingGk)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel12))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnHuy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLuu)
                                .addGap(15, 15, 15))))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(lbTotalStartingPlayer)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(lbTotalStartingGk)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbTotalSub)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHuy)
                            .addComponent(btnLuu))
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemDaChinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDaChinhActionPerformed
        int selectedRow = tbDanhSach.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ!");
            return;
        }
        
        int id = (int) tbDanhSach.getValueAt(selectedRow, 0);
        Player player = map.get(id);
        
        boolean isGk = player.getPosition().equals(PlayerPosition.GOALKEEPER);
        
        if(totalStarting >= 5){
            JOptionPane.showMessageDialog(this, "Số lượng cầu thủ đá chính không được vượt quá 5!");
            return;
        }
        
        if(isGk && totalGk == 1){
            JOptionPane.showMessageDialog(this, "Chỉ có 1 GoalKeeper được tham gia đá chính");
            return;
        }
        
        if(!isGk && totalNor == 4){
            JOptionPane.showMessageDialog(this, "Cầu thủ còn lại phải là GoalKeeper");
            return;
        }
        
        daChinh.add(player);
        
        totalStarting++;
        if(isGk) totalGk++;
        else totalNor++;
        
        modelDanhSach.removeRow(selectedRow);
        modelDaChinh.addRow(new Object[]{player.getPlayerId(), player.getPlayerName(), player.getPosition().name()});
        
        updateLabelCount();
    }//GEN-LAST:event_btnThemDaChinhActionPerformed

    private void btnThemDuBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDuBiActionPerformed
        int selectedRow = tbDanhSach.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ!");
            return;
        }
        
        int id = (int) tbDanhSach.getValueAt(selectedRow, 0);
        Player player = map.get(id);
        
        if(totalSub >= 6){
            JOptionPane.showMessageDialog(this, "Số lượng cầu thủ dự bị không được vượt quá 6!");
            return;
        }
        
        duBi.add(player);
        
        totalSub++;
        
        modelDanhSach.removeRow(selectedRow);
        modelDuBi.addRow(new Object[]{player.getPlayerId(), player.getPlayerName(), player.getPosition().name()});
        
        updateLabelCount();
    }//GEN-LAST:event_btnThemDuBiActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int selectedRowTbDaChinh = tbDaChinh.getSelectedRow();
        int selectedRowDuBi = tbDuBi.getSelectedRow();
        if(selectedRowTbDaChinh == -1 && selectedRowDuBi == -1){
            JOptionPane.showMessageDialog(this, "Vui lòng chọn 1 cầu thủ!");
            return;
        }
        
        if(selectedRowTbDaChinh != -1 && selectedRowDuBi != -1){
            JOptionPane.showMessageDialog(this, "Chỉ được chọn 1 cầu thủ ở 1 trong 2 bảng!");
            return;
        }
        
        Player player;
        
        if(selectedRowTbDaChinh != -1){
            int id = (int) tbDaChinh.getValueAt(selectedRowTbDaChinh, 0);
            modelDaChinh.removeRow(selectedRowTbDaChinh);
            player = map.get(id);
            boolean isGk = player.getPosition().equals(PlayerPosition.GOALKEEPER);
            totalStarting--;
            if(isGk) totalGk--;
            else totalNor--;
            daChinh.remove(player);
        }
        else {
            int id = (int) tbDuBi.getValueAt(selectedRowDuBi, 0);
            modelDuBi.removeRow(selectedRowDuBi);
            player = map.get(id);
            totalSub--;
            duBi.remove(player);
        }
        
        modelDanhSach.addRow(new Object[]{player.getPlayerId(), player.getPlayerName(), player.getPosition().name()});
        
        updateLabelCount();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        if(totalStarting < 5){
            JOptionPane.showMessageDialog(this, "Chưa đủ số lượng cầu đá chính!");
            return;
        }
        
        if(totalSub < 6){
            JOptionPane.showMessageDialog(this, "Chưa đủ số lượng cầu thủ dự bị!");
            return;
        }
        
        if(!isSelectedPlayer){
            isConfirm = true;
            dispose();
            return;
        }
        
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Đổi danh sách cầu thủ sẽ xóa toàn bộ danh sách sự kiện có liên quan!",
            "Xác nhận cập nhật",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        if(choice == JOptionPane.YES_OPTION){
            isConfirm = true;
            dispose();
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void getPlayerList(){
        try {
            PlayerService service = new PlayerService();
            list = service.getPlayersByTeamID(teamId);
            map = list.stream().collect(Collectors.toMap(player -> player.getPlayerId(), player -> player));
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void initTableDanhSachData(){
        modelDanhSach.setRowCount(0);
        for(Player player : list){
            modelDanhSach.addRow(new Object[]{player.getPlayerId(), player.getPlayerName(), player.getPosition().name()});
        }
    }
    
    private void initLabelTeamName(){
        try{
            TeamService service = new TeamService();
            Team team = service.getTeamById(teamId);
            lbTenDoi.setText(team.getTeamName());
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void updateLabelCount(){
        lbTotalStartingPlayer.setText("" + totalStarting);
        lbTotalSub.setText("" + totalSub);
        lbTotalStartingGk.setText("" + totalGk);
    }
    
    private void initTableSelectionListener(){
        tbDanhSach.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tbDanhSach.getSelectedRow() != -1) { // Chỉ xử lý khi quá trình chọn kết thúc và có hàng được chọn
                // Bỏ chọn ở hai bảng còn lại
                tbDaChinh.clearSelection(); 
                tbDuBi.clearSelection();

                // Cập nhật trạng thái nút
                updateOnClickDanhSach();
            } else if (!e.getValueIsAdjusting() && tbDanhSach.getSelectedRow() == -1) {
                // Trường hợp không còn hàng nào được chọn sau khi xóa/bỏ chọn
                updateOnClickDanhSach();
            }
        }); 

        // Listener cho tbDaChinh
        tbDaChinh.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tbDaChinh.getSelectedRow() != -1) {
                // Bỏ chọn ở hai bảng còn lại
                tbDanhSach.clearSelection();
                tbDuBi.clearSelection();

                // Cập nhật trạng thái nút
                updateOnClickDaChinh();
            } else if (!e.getValueIsAdjusting() && tbDaChinh.getSelectedRow() == -1) {
                 updateOnClickDaChinh();
            }
        }); 

        // Listener cho tbDuBi
        tbDuBi.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && tbDuBi.getSelectedRow() != -1) {
                // Bỏ chọn ở hai bảng còn lại
                tbDanhSach.clearSelection();
                tbDaChinh.clearSelection();

                // Cập nhật trạng thái nút
                updateOnClickDuBi();
            } else if (!e.getValueIsAdjusting() && tbDuBi.getSelectedRow() == -1) {
                 updateOnClickDuBi();
            }
        });
    }
    
    private void updateOnClickDanhSach(){
        
        if (tbDanhSach.getSelectedRow() == -1) { // <-- Thêm kiểm tra này
            btnThemDaChinh.setEnabled(false);
            btnThemDuBi.setEnabled(false);
            btnXoa.setEnabled(false);
            return;
        }
        
        int selectedCount = tbDanhSach.getSelectedRowCount();
        
        boolean enable = (selectedCount == 1);
        boolean isPlayerGk = tbDanhSach.getValueAt(tbDanhSach.getSelectedRow(), 2).toString().equalsIgnoreCase(PlayerPosition.GOALKEEPER.name());
        boolean isOk = isPlayerGk ? totalGk < 1 : totalNor < 5;
        btnThemDaChinh.setEnabled(enable && totalStarting < 5 && isOk);
        btnThemDuBi.setEnabled(enable && totalSub < 6);
        btnXoa.setEnabled(false);
    }
    
    private void updateOnClickDaChinh(){
        if (tbDaChinh.getSelectedRow() == -1) { // <-- Thêm kiểm tra này
            btnThemDaChinh.setEnabled(false);
            btnThemDuBi.setEnabled(false);
            btnXoa.setEnabled(false);
            return;
        }
                
        int selectedCount = tbDaChinh.getSelectedRowCount();
        boolean enable = (selectedCount == 1);
        btnThemDaChinh.setEnabled(false);
        btnThemDuBi.setEnabled(false);
        btnXoa.setEnabled(enable);
    }
    
    private void updateOnClickDuBi(){
        if (tbDuBi.getSelectedRow() == -1) { // <-- Thêm kiểm tra này
            btnThemDaChinh.setEnabled(false);
            btnThemDuBi.setEnabled(false);
            btnXoa.setEnabled(false);
            return;
        }
        
        int selectedCount = tbDuBi.getSelectedRowCount();
        boolean enable = (selectedCount == 1);
        btnThemDaChinh.setEnabled(false);
        btnThemDuBi.setEnabled(false);
        btnXoa.setEnabled(enable);
    }
    
    public List<Player> getStartingList(){
        if(daChinh.size() != 5) System.out.println("Chua du so luong cau thu da chinh");
        return daChinh;
    }
    
    public List<Player> getSubList(){
        if(duBi.size() != 6) System.out.println("Chua du so luong cau thu du bi");
        return duBi;
    }
    
    public boolean isConfirm(){
        return isConfirm;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ChonDoiHinhDialog dialog = new ChonDoiHinhDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnThemDaChinh;
    private javax.swing.JButton btnThemDuBi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbTenDoi;
    private javax.swing.JLabel lbTotalStartingGk;
    private javax.swing.JLabel lbTotalStartingPlayer;
    private javax.swing.JLabel lbTotalSub;
    private javax.swing.JTable tbDaChinh;
    private javax.swing.JTable tbDanhSach;
    private javax.swing.JTable tbDuBi;
    // End of variables declaration//GEN-END:variables
}
