/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package N23DCCN058.fm.ui.dialog;

import N23DCCN058.fm.model.Team;
import N23DCCN058.fm.service.TeamService;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author WokWee
 */
public class ChonDoiDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChonDoiDialog.class.getName());

    /**
     * Creates new form ChonDoiDIalog
     */
    
    private int idHomeTeam, idAwayTeam;
    private boolean isSelectedTeam, isConfirm;
    private List<Team> lstTeam;
    
    
    public ChonDoiDialog(java.awt.Frame parent, boolean modal) {
        this(parent, modal,false, -1, -1);
    }
    
    public ChonDoiDialog(java.awt.Frame parent, boolean modal,boolean isSelectedTeam, int homeTeam, int awayTeam) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(parent);
        
        this.isSelectedTeam = isSelectedTeam;
        this.idHomeTeam = homeTeam;
        this.idAwayTeam = awayTeam;
        
        
        getListTeam();
        initComboBoxData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbDoiKhach = new javax.swing.JComboBox<>();
        cbDoiNha = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Chọn đội nhà:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Chọn đội khách:");

        cbDoiKhach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDoiNha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setBackground(new java.awt.Color(0, 76, 127));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Xác nhận");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 76, 127));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hủy");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(cbDoiNha, 0, 269, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbDoiKhach, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbDoiNha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbDoiKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Integer newIdHome = getHomeTeam();
        Integer newIdAway = getAwayTeam();
        
        if(newIdHome == null || newIdAway == null || newIdHome <= 0 || newIdAway <= 0){
            JOptionPane.showMessageDialog(this, "Phải chọn đủ hai đội bóng tham gia", "Chưa chọn đủ thông tin", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(newIdHome == newIdAway){
            JOptionPane.showMessageDialog(this, "Không được chọn hai đội giống nhau", "Chưa chọn đủ thông tin", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(newIdHome == idHomeTeam && newIdAway == idAwayTeam) dispose();
        
        this.idHomeTeam = newIdHome;
        this.idAwayTeam = newIdAway;
        
        if(!isSelectedTeam){
            isConfirm = true;
            dispose();
            return;
        }
        
        int choice = JOptionPane.showConfirmDialog(
            this,
            "Đổi đội bóng sẽ xóa toàn bộ danh sách cầu thủ và danh sách sự kiện có liên quan!",
            "Xác nhận cập nhật",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );
        
        if(choice == JOptionPane.YES_OPTION){
            isConfirm = true;
            dispose();
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private Integer getHomeTeam(){
        String tenDoiBong = (String) cbDoiNha.getSelectedItem();
        int idx;
        for(idx = 0; idx < lstTeam.size(); idx++){
            if(lstTeam.get(idx).getTeamName().equalsIgnoreCase(tenDoiBong)) break;
        }
        return idx >= lstTeam.size() ? null : lstTeam.get(idx).getTeamId();
    }
    
    private Integer getAwayTeam(){
        String tenDoiBong = (String) cbDoiKhach.getSelectedItem();
        int idx;
        for(idx = 0; idx < lstTeam.size(); idx++){
            if(lstTeam.get(idx).getTeamName().equalsIgnoreCase(tenDoiBong)) break;
        }
        return idx >= lstTeam.size() ? null : lstTeam.get(idx).getTeamId();
    }
    
    private void getListTeam(){
        try {
            TeamService service = new TeamService();
            lstTeam = service.getAllTeam();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void initComboBoxData(){
        cbDoiNha.removeAllItems();
        cbDoiKhach.removeAllItems();
        
        for(Team team: lstTeam){
            cbDoiNha.addItem(team.getTeamName());
            cbDoiKhach.addItem(team.getTeamName());
        }
        
        if(!isSelectedTeam){
            cbDoiNha.setSelectedIndex(-1);
            cbDoiKhach.setSelectedIndex(-1);
        }
        else {
            try {
            TeamService service = new TeamService();
                cbDoiNha.setSelectedItem(service.getTeamById(idHomeTeam).getTeamName());
                cbDoiKhach.setSelectedItem(service.getTeamById(idAwayTeam).getTeamName());
            } catch(Exception e){
                e.printStackTrace();
            }
        }
        
    }
    
    public boolean isConfirm(){
        return isConfirm;
    }
    
    public int getHomeTeamId(){
        return this.idHomeTeam;
    }
    
    public int getAwayTeamId(){
        return this.idAwayTeam;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ChonDoiDialog dialog = new ChonDoiDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDoiKhach;
    private javax.swing.JComboBox<String> cbDoiNha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
