/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package N23DCCN058.fm.ui.dialog;

import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.PlayerPosition;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author WokWee
 */
public class ChonCauThuThayVaoDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChonCauThuThayVaoDialog.class.getName());

    /**
     * Creates new form ChonCauThuThayVaoDialog
     */
    
    private  Map<Integer, Player> player;
    private Map<Integer, PlayerPosition> positions;
    private Set<Integer> playerOnField, playerGetRedCard;
    private boolean isConfirm;
    
    public ChonCauThuThayVaoDialog(java.awt.Frame parent, boolean modal){
        this(parent, modal, null, null,null);
    }

    public ChonCauThuThayVaoDialog(java.awt.Frame parent, boolean modal, Map<Integer, Player> player, Set<Integer> playerOnField, Set<Integer> playerGetRedCard) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(parent);
        
        this.player = player;
        this.playerOnField = playerOnField;
        this.playerGetRedCard = playerGetRedCard;
        
        initTable();
    }
    
    public ChonCauThuThayVaoDialog(java.awt.Window parent, boolean modal, Map<Integer, Player> player, Set<Integer> playerOnField, Set<Integer> playerGetRedCard, Map<Integer, PlayerPosition> positions) {
        super(parent, modal ? ModalityType.APPLICATION_MODAL : ModalityType.MODELESS);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(parent);
        
        this.player = player;
        this.playerOnField = playerOnField;
        this.playerGetRedCard = playerGetRedCard;
        this.positions = positions;
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCauThu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnChon = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 200));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(200, 100));

        tbCauThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCauThu);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 76, 127));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHỌN CẦU THỦ THAY VÀO");

        btnChon.setBackground(new java.awt.Color(0, 76, 127));
        btnChon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChon.setForeground(new java.awt.Color(255, 255, 255));
        btnChon.setText("CHỌN");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(0, 76, 127));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("HỦY");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnHuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChon)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChon)
                    .addComponent(btnHuy))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean isConfirm(){
        return isConfirm;
    }
    
    private void initTableSelectionListener(){
        tbCauThu.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) { // Đảm bảo chỉ xử lý khi chọn xong
                int selectedCount = tbCauThu.getSelectedRowCount();
                
                btnChon.setEnabled(selectedCount == 1);
            }   
        }); 
    }
    
    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        int selectedRow = tbCauThu.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Chọn một cầu thủ để thêm sự kiện");
            return;
        }
        isConfirm = true;
        dispose();
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    public Player getPlayer(){
        int selectedRow = tbCauThu.getSelectedRow();
        int id = (int) tbCauThu.getValueAt(selectedRow, 0);
        return player.get(id);
    }
    
    private void initTable() {
        String[] columnNames = {"Id", "Tên cầu thủ", "Vị trí"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0);
        tbCauThu.setModel(model);
        
        tbCauThu.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel col = tbCauThu.getColumnModel();
        
        col.getColumn(0).setPreferredWidth(40); // Id cầu thủ
        col.getColumn(1).setPreferredWidth(140); // Tên cầu thủ
        col.getColumn(2).setPreferredWidth(100); // Ngày sinh
        
        for (int i = 0; i < col.getColumnCount(); i++) {
            col.getColumn(i).setResizable(false);
        }
        
        for(Map.Entry<Integer, Player> entry : player.entrySet()){
            
            if(!playerOnField.contains(entry.getKey()) && !playerGetRedCard.contains(entry.getKey())){
                Player p = entry.getValue();
                model.addRow(new Object[]{p.getPlayerId(), p.getPlayerName(), positions.get(p.getPlayerId()).name()});
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ChonCauThuThayVaoDialog dialog = new ChonCauThuThayVaoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCauThu;
    // End of variables declaration//GEN-END:variables

    
}
