/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package N23DCCN058.fm.ui.dialog;

import N23DCCN058.fm.model.FinishedMatchDetails;
import N23DCCN058.fm.service.FinishedMatchDetailsService;
import N23DCCN058.fm.service.RefereeService;
import N23DCCN058.fm.service.TeamService;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author WokWee
 */
public class ChonTranDauExportDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChonTranDauExportDialog.class.getName());

    /**
     * Creates new form ChonTranDauExportDialog
     */
    private DefaultTableModel model;
    private boolean isConfirm;
    private int selectedMatch;
    
    public ChonTranDauExportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(parent);
        
        String[] columnNames = {"Id", "Đôi nhà", "Đội khách", "Ngày", "Trọng tài"};
        model = new DefaultTableModel(columnNames, 0);
        tbTranDau.setModel(model);
        
        tbTranDau.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel colDaChinh = tbTranDau.getColumnModel();
        
        colDaChinh.getColumn(0).setPreferredWidth(30); // Id cầu thủ
        colDaChinh.getColumn(1).setPreferredWidth(125); // Tên cầu thủ
        colDaChinh.getColumn(2).setPreferredWidth(125); // Ngày sinh
        colDaChinh.getColumn(3).setPreferredWidth(100); // Id cầu thủ
        colDaChinh.getColumn(4).setPreferredWidth(125); // Tên cầu thủ
        
        for (int i = 0; i < colDaChinh.getColumnCount(); i++) {
            colDaChinh.getColumn(i).setResizable(false);
        }
        
        initTableData();
    }
    
    public ChonTranDauExportDialog(java.awt.Window parent, boolean modal) {
        super(parent, modal ? ModalityType.APPLICATION_MODAL : ModalityType.MODELESS);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(parent);
        
        String[] columnNames = {"Id", "Đôi nhà", "Đội khách", "Ngày", "Trọng tài"};
        model = new DefaultTableModel(columnNames, 0);
        tbTranDau.setModel(model);
        
        tbTranDau.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel colDaChinh = tbTranDau.getColumnModel();
        
        colDaChinh.getColumn(0).setPreferredWidth(35); // Id cầu thủ
        colDaChinh.getColumn(1).setPreferredWidth(130); // Tên cầu thủ
        colDaChinh.getColumn(2).setPreferredWidth(130); // Ngày sinh
        colDaChinh.getColumn(3).setPreferredWidth(80); // Id cầu thủ
        colDaChinh.getColumn(4).setPreferredWidth(130); // Tên cầu thủ
        
        for (int i = 0; i < colDaChinh.getColumnCount(); i++) {
            colDaChinh.getColumn(i).setResizable(false);
        }
        
        initTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTranDau = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("DANH SÁCH TRẬN ĐẤU : ");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 220));

        tbTranDau.setAutoCreateRowSorter(true);
        tbTranDau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbTranDau);

        jButton1.setBackground(new java.awt.Color(0, 76, 127));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CHỌN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 76, 127));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("HỦY");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = tbTranDau.getSelectedRow();
        
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Chọn một trận đấu để export!");
            return;
        }
        
        this.selectedMatch = (int) tbTranDau.getValueAt(selectedRow, 0);
        isConfirm = true;
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public int getMatchId(){
        return this.selectedMatch;
    }
    
    public boolean isConfirm(){
        return this.isConfirm;
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void initTableData(){
        try {
            FinishedMatchDetailsService fmdService = new FinishedMatchDetailsService();
            TeamService teamService = new TeamService();
            RefereeService refereeService = new RefereeService();
            
            List<FinishedMatchDetails> list = fmdService.getAllMatchDetail();
            Map<Integer, String> teamName = teamService.getAllTeam()
                    .stream()
                    .collect(Collectors.toMap(
                            Team -> Team.getTeamId(),
                            Team -> Team.getTeamName()
                    ));
            Map<Integer, String> refereeName = refereeService.getAllReferee()
                    .stream()
                    .collect(Collectors.toMap(
                            Referee -> Referee.getRefereeId(),
                            Referee -> Referee.getRefereeName()
                    ));
            
            for(FinishedMatchDetails m : list){
                model.addRow(new Object[]{m.getMatchId(), teamName.get(m.getHomeTeam()), teamName.get(m.getAwayTeam()), m.getMatchDate(), refereeName.get(m.getRefereeId())});
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ChonTranDauExportDialog dialog = new ChonTranDauExportDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTranDau;
    // End of variables declaration//GEN-END:variables
}
