/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package N23DCCN058.fm.ui.dialog;

import N23DCCN058.fm.model.ErrorDetail;
import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.Referee;
import N23DCCN058.fm.model.Team;
import N23DCCN058.fm.service.PlayerService;
import N23DCCN058.fm.service.RefereeService;
import N23DCCN058.fm.service.TeamService;
import N23DCCN058.fm.service.TournamentService;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import static org.apache.poi.hssf.usermodel.HeaderFooter.file;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author WokWee
 */
public class ImportDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ImportDialog.class.getName());

    /**
     * Creates new form ImportDialog
     */
    private boolean isConfirm;
    
    public ImportDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(parent);
        
        cbDuLieu.removeAllItems();
        cbDuLieu.addItem("Đội bóng");
        cbDuLieu.addItem("Cầu thủ");
        cbDuLieu.addItem("Trọng tài");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cbDuLieu = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Loại dữ liệu : ");

        cbDuLieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDuLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDuLieuActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("File :");

        jButton1.setBackground(new java.awt.Color(0, 76, 127));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 76, 127));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Import");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 76, 127));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Hủy");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbDuLieu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDuLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean validateExcelStructure(Sheet sheet, List<String> requiredColumns) {

        Row header = sheet.getRow(0);
        if (header == null) return false;

        int excelColumnCount = header.getLastCellNum();
        int requiredColumnCount = requiredColumns.size();

        // Kiểm tra số lượng cột có đúng hay không
        if (excelColumnCount != requiredColumnCount) {
            return false;
        }

        // Kiểm tra từng tên cột theo đúng thứ tự
        for (int i = 0; i < requiredColumnCount; i++) {
            Cell cell = header.getCell(i);
            String colName = (cell != null) ? cell.getStringCellValue().trim() : "";

            if (!colName.equalsIgnoreCase(requiredColumns.get(i))) {
                return false;
            }
        }

        return true;
    }
    
    public boolean validateTeamExcel(Sheet sheet) {
        List<String> required = Arrays.asList(
            "Tên đội bóng",
            "Phòng ban",
            "Tên huấn luyện viên"
        );

        return validateExcelStructure(sheet, required);
    }
    
    public boolean validatePlayerExcel(Sheet sheet) {
        List<String> required = Arrays.asList(
            "Tên",
            "Ngày sinh",
            "Số áo",
            "Vị trí",
            "Tên đội"
        );

        return validateExcelStructure(sheet, required);
    }
    
    public boolean validateRefereeExcel(Sheet sheet) {
        List<String> required = Arrays.asList(
            "Tên",
            "Số điện thoại"
        );

        return validateExcelStructure(sheet, required);
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txtFilePath.getText() == null || txtFilePath.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Chọn một file để import!");
            return;
        }
        
        Workbook workbook = null;
        try {
            workbook = new XSSFWorkbook(new FileInputStream(txtFilePath.getText()));
        } catch (FileNotFoundException ex) {
            System.getLogger(ImportDialog.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IOException ex) {
            System.getLogger(ImportDialog.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        Sheet sheet = workbook.getSheetAt(0);

        boolean valid = false;

        switch (cbDuLieu.getSelectedItem().toString()) {
            case "Đội bóng":
                valid = validateTeamExcel(sheet);
                break;

            case "Cầu thủ":
                valid = validatePlayerExcel(sheet);
                break;

            case "Trọng tài":
                valid = validateRefereeExcel(sheet);
                break;
        }

        if (!valid) {
            JOptionPane.showMessageDialog(this,
                "File Excel không đúng cấu trúc đối với loại dữ liệu đã chọn!",
                "Sai cấu trúc",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            TournamentService service = new TournamentService();
            TeamService teamService = new TeamService();
            PlayerService playerService = new PlayerService();
            RefereeService refereeService = new RefereeService();
            List<ErrorDetail> errors = null;
            
            switch (cbDuLieu.getSelectedItem().toString()) {
                case "Đội bóng":
                    List<Team> teams = service.readTeamsFromExcel(txtFilePath.getText());
                    errors = teamService.validateTeams(teams);
                    if(errors.isEmpty()) teamService.addTeams(teams);
                    break;
                case "Cầu thủ":
                    List<Player> players = service.readPlayersFromExcel(txtFilePath.getText());
                    errors = playerService.validatePlayers(players);
                    if(errors.isEmpty()) playerService.addPlayers(players);
                    break;
                case "Trọng tài":
                    List<Referee> referees = service.readRefereesFromExcel(txtFilePath.getText());
                    errors = refereeService.validateReferees(referees);
                    if(errors.isEmpty()) refereeService.addReferees(referees);
            }
            
            if(!errors.isEmpty()){
                String message = "Dữ liệu không hợp lệ: ";
                for(ErrorDetail er : errors){
                    message += "\nDòng " + er.getRowIndex() + ": " + er.getMessage();
                }
                JOptionPane.showMessageDialog(this, message, "Lỗi dữ liệu", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, "Import thành công!");
                dispose();
            }
            
        
        }catch(Exception e){
            e.printStackTrace();
        }
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDuLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDuLieuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel Files", "xlsx");
        chooser.setFileFilter(filter);

        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            txtFilePath.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ImportDialog dialog = new ImportDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDuLieu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFilePath;
    // End of variables declaration//GEN-END:variables
}
