/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package N23DCCN058.fm.ui.dialog;

import N23DCCN058.fm.exception.ValidationException;
import N23DCCN058.fm.model.EventType;
import N23DCCN058.fm.model.MatchEvents;
import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.PlayerPosition;
import N23DCCN058.fm.model.Team;
import N23DCCN058.fm.service.MatchEventService;
import N23DCCN058.fm.service.TeamService;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author WokWee
 */
public class ThemSuKienDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ThemSuKienDialog.class.getName());

    /**
     * Creates new form ThemSuKienDialog
     */
    private int matchId, lastEventTime;
    private Team home, away;
    private Map<Integer, Player> playerHome, playerAway;
    private Set<Integer> homePlayerOnField, awayPlayerOnField, playerGetRedCard;
    private DefaultTableModel model, homeModel, awayModel;
    private SpinnerNumberModel spinnerModel;
    private boolean isConfirm;
    private Player additionPlayer;
    private Map<Integer, PlayerPosition> positions;
    
    public ThemSuKienDialog(java.awt.Frame parent, boolean modal){
        this(parent, modal, -1, null, null, null, null, null, null,null,null, -1);
    }
    
    
    public ThemSuKienDialog(java.awt.Frame parent, boolean modal
            , int matchId
            , Team home
            , Team away
            , Map<Integer, Player> playerHome
            , Map<Integer, Player> playerAway
            , Set<Integer> homePlayerOnField
            , Set<Integer> awayPlayerOnField
            , Set<Integer> playerGetRedCard
            , Map<Integer, PlayerPosition> positions
            , int lastEventTime
                ){
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(parent);
        
        this.matchId = matchId;
        this.home = home;
        this.away = away;
        this.playerHome = playerHome;
        this.playerAway = playerAway;
        this.homePlayerOnField = homePlayerOnField;
        this.awayPlayerOnField = awayPlayerOnField;
        this.playerGetRedCard = playerGetRedCard;
        this.lastEventTime = lastEventTime;
        this.positions = positions;
        
        initTablePlayer();
        initModelHome();
        initModelAway();
        initEventType();
        initSpinner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCauThu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbLoaiSuKien = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        spThoiGian = new javax.swing.JSpinner();
        btnThem = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbTenDialog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 250));

        tbCauThu.setAutoCreateRowSorter(true);
        tbCauThu.setPreferredSize(new java.awt.Dimension(400, 250));
        jScrollPane1.setViewportView(tbCauThu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setText("Sự kiện :");

        cbLoaiSuKien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Thời gian :");

        btnThem.setBackground(new java.awt.Color(0, 76, 127));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnHuy.setBackground(new java.awt.Color(0, 76, 127));
        btnHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(0, 76, 127));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cầu thủ đội nhà");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 76, 127));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cầu thủ đội khách");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lbTenDialog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbTenDialog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTenDialog.setText("THÊM SỰ KIỆN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTenDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spThoiGian)
                                    .addComponent(cbLoaiSuKien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnHuy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThem)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTenDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbLoaiSuKien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initSpinner(){
        spinnerModel = new SpinnerNumberModel(lastEventTime, 0, 60, 1);
        spThoiGian.setModel(spinnerModel);
    }
    
    private void initEventType(){
        cbLoaiSuKien.removeAllItems();
        cbLoaiSuKien.addItem(EventType.GOAL.getVietnamese());
        cbLoaiSuKien.addItem(EventType.PENALTY_GOAL.getVietnamese());
        cbLoaiSuKien.addItem(EventType.OWN_GOAL.getVietnamese());
        cbLoaiSuKien.addItem(EventType.FOUL.getVietnamese());
        cbLoaiSuKien.addItem(EventType.YELLOW_CARD.getVietnamese());
        cbLoaiSuKien.addItem(EventType.RED_CARD.getVietnamese());
        cbLoaiSuKien.addItem(EventType.SUBSTITUTION_OUT.getVietnamese());
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       tbCauThu.setModel(homeModel);
       tbCauThu.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel col = tbCauThu.getColumnModel();
        
        col.getColumn(0).setPreferredWidth(40); 
        col.getColumn(1).setPreferredWidth(130); 
        col.getColumn(2).setPreferredWidth(130); 
        col.getColumn(3).setPreferredWidth(100);
        
        for (int i = 0; i < col.getColumnCount(); i++) {
            col.getColumn(i).setResizable(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tbCauThu.setModel(awayModel);
        tbCauThu.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel col = tbCauThu.getColumnModel();
        
        col.getColumn(0).setPreferredWidth(40); 
        col.getColumn(1).setPreferredWidth(130); 
        col.getColumn(2).setPreferredWidth(130); 
        col.getColumn(3).setPreferredWidth(100);
        
        for (int i = 0; i < col.getColumnCount(); i++) {
            col.getColumn(i).setResizable(false);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public MatchEvents getEvent(){
        int selectedRow = tbCauThu.getSelectedRow();
        int id = (int) tbCauThu.getValueAt(selectedRow, 0);
        return new MatchEvents(matchId, id, EventType.fromVietnamese(cbLoaiSuKien.getSelectedItem().toString()), (Integer) spThoiGian.getValue());
    }
    
    public MatchEvents getSubtitutionIn(){
        return new MatchEvents(matchId, additionPlayer.getPlayerId(), EventType.SUBSTITUTION_IN,  (Integer) spThoiGian.getValue());
    }
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        int selectedRow = tbCauThu.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Chọn một cầu thủ để thêm sự kiện");
            return;
        }
        try {
            MatchEventService mtService = new MatchEventService();
            if(!mtService.isEventValid(getEvent())) return;
            
        } catch(ValidationException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Dữ liệu không hợp lệ", JOptionPane.ERROR_MESSAGE);
        }
        
        int id = getEvent().getPlayerId();
        
        if(getEvent().getEventType().equals(EventType.SUBSTITUTION_OUT)){
            ChonCauThuThayVaoDialog dialog;
            if(playerHome.containsKey(id)) dialog = new ChonCauThuThayVaoDialog(this, true, playerHome, homePlayerOnField,playerGetRedCard, positions);
            else dialog = new ChonCauThuThayVaoDialog(this, true, playerAway, awayPlayerOnField,playerGetRedCard, positions);
            dialog.setVisible(true);
            
            if(!dialog.isConfirm()) return;
            
            this.additionPlayer = dialog.getPlayer();
        }
        
        isConfirm = true;
        dispose();
    }//GEN-LAST:event_btnThemActionPerformed

    public boolean isConfirm(){
        return isConfirm;
    }
    
    private void initModelHome(){
        for(Integer id : homePlayerOnField){
            Player player = playerHome.get(id);
            homeModel.addRow(new Object[]{player.getPlayerId(), player.getPlayerName(), home.getTeamName(), positions.get(player.getPlayerId()).name()});
        }
    }
    
    private void initModelAway(){
        for(Integer id : awayPlayerOnField){
            Player player = playerAway.get(id);
            awayModel.addRow(new Object[]{player.getPlayerId(), player.getPlayerName(), away.getTeamName(), positions.get(player.getPlayerId()).name()});
        }
    }
    
    
    private void initTablePlayer(){
        String[] columnNames = {"Id", "Tên cầu thủ", "Tên đội", "Vị trí"};
        model = new DefaultTableModel(columnNames, 0);
        homeModel = new DefaultTableModel(columnNames, 0);
        awayModel = new DefaultTableModel(columnNames, 0);
        tbCauThu.setModel(model);
        
        tbCauThu.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        
        TableColumnModel col = tbCauThu.getColumnModel();
        
        col.getColumn(0).setPreferredWidth(40); 
        col.getColumn(1).setPreferredWidth(130); 
        col.getColumn(2).setPreferredWidth(130); 
        col.getColumn(3).setPreferredWidth(100);
        
        for (int i = 0; i < col.getColumnCount(); i++) {
            col.getColumn(i).setResizable(false);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ThemSuKienDialog dialog = new ThemSuKienDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbLoaiSuKien;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTenDialog;
    private javax.swing.JSpinner spThoiGian;
    private javax.swing.JTable tbCauThu;
    // End of variables declaration//GEN-END:variables
}
