/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package N23DCCN058.fm.ui.dialog;

import N23DCCN058.fm.exception.ServiceException;
import N23DCCN058.fm.model.Player;
import N23DCCN058.fm.model.Team;
import N23DCCN058.fm.service.TeamService;
import java.awt.Cursor;
import java.util.List;

/**
 *
 * @author admin
 */
public class TimCauThuTheoTenDoiBongDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TimCauThuTheoTenDoiBongDialog.class.getName());

    /**
     * Creates new form TimKiemTheoDoiDialog
     */
    private List<Team> lst;
    private boolean isConfirm;
    
    public TimCauThuTheoTenDoiBongDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(parent);
        btnTimKiem.setOpaque(false);
        btnTimKiem.setBorderPainted(false);     // bỏ viền
        btnTimKiem.setContentAreaFilled(false); // bỏ nền
        btnTimKiem.setFocusPainted(false);      // bỏ viền focus khi click
        btnTimKiem.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        initCBTenDoi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTimKiem = new javax.swing.JButton();
        cbTenDoi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 80));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 80));

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/fm/icons/tìm kiếm-15(30 x 30).png"))); // NOI18N
        btnTimKiem.setMaximumSize(new java.awt.Dimension(30, 30));
        btnTimKiem.setMinimumSize(new java.awt.Dimension(30, 30));
        btnTimKiem.setPreferredSize(new java.awt.Dimension(30, 30));
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        cbTenDoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cbTenDoi, 0, 536, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbTenDoi))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initCBTenDoi(){
        try {
            TeamService ts = new TeamService();
            lst = ts.getAllTeam();
            cbTenDoi.removeAllItems();
            for(Team team : lst) cbTenDoi.addItem(team.getTeamName());
        } catch(ServiceException e){
            e.printStackTrace();
        }
    }
    
    public boolean isConfirm(){
        return isConfirm;
    }
    
    public int getTeamId(){
        String teamName = (String) cbTenDoi.getSelectedItem();
        int idx = 0;
        for(idx = 0; idx < lst.size(); idx++){
            if(lst.get(idx).getTeamName().equalsIgnoreCase(teamName)) break;
        }
        return lst.get(idx).getTeamId();
    }
    
    
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String teamName = (String) cbTenDoi.getSelectedItem();
        if(teamName == null || teamName.trim().isBlank()){
            dispose();
            return;
        }
        isConfirm = true;
        dispose();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TimCauThuTheoTenDoiBongDialog dialog = new TimCauThuTheoTenDoiBongDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbTenDoi;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
